#!/usr/bin/env python3
"""codegen_dafny.py — the trust chain.

Reads facts.json + claims-narrative.json + claims-coaching.json and GENERATES all
Dafny source under ./dafny. NO per-round statistic is ever hand-typed in a .dfy
file: every data literal is emitted here from facts.json.

Design
------
* Facts.dfy — FLAT named scalar consts, one per datum the 54 claims reference:
      const m{mi}_r{ri}_{player}_{field}: int := <value>;   // from facts.json
      const m{mi}_r{ri}_winner: string := "..."; etc.
  A flat const is a transparent literal to Z3, so every proof below reduces to
  literal arithmetic — no seq indexing, no datatype destructors, no recursion,
  no proof hints. (An earlier nested `seq<Match>` design made Z3 deep-index one
  giant literal and timed out; flat consts fix that at the root.)
  Fields carried = only those referenced by the claims (omissions documented in
  the Facts.dfy header). ge (garbage_events amt) consts are emitted for yachi
  only, since R019 is the sole claim reading them.
* Claims_narrative.dfy / Claims_coaching.dfy — ONE lemma per claim, id-named,
  whose ensures-clause is a faithful translation of that claim's python_check
  over the flat consts. Bodies are empty; the consts evaluate directly.
* Winner/loser-relative reads (`r['players'][r['winner']]`) are translated with
  an if-then-else on the winner-string const, so a mutated winner still changes
  which datum is selected (mutation-faithful).

Usage: python3 codegen_dafny.py            # writes dafny/*.dfy + claims-proof-map.json
"""
import json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "dafny")

facts = json.load(open(os.path.join(HERE, "facts.json")))
MS = facts["matches"]

PY = {
    "lifetime": lambda p: p["lifetime"],
    "apm": lambda p: p["apm_x1000"],
    "pps": lambda p: p["pps_x1000"],
    "vs": lambda p: p["vs_x1000"],
    "garbagereceived": lambda p: p["garbagereceived"],
    "lines": lambda p: p["lines"],
    "pieces": lambda p: p["pieces"],
    "holds": lambda p: p["holds"],
    "topcombo": lambda p: p["topcombo"],
    "topbtb": lambda p: p["topbtb"],
    "tspins": lambda p: p["tspins"],
    "quads": lambda p: p["clears"]["quads"],
    "tspinDoubles": lambda p: p["clears"]["tspin_doubles"],
    "tspinTriples": lambda p: p["clears"]["tspin_triples"],
    "allclear": lambda p: p["clears"]["allclear"],
    "garbageAttack": lambda p: p["garbage_attack"],
    "garbageCleared": lambda p: p["garbage_cleared"],
    "maxspike": lambda p: p["maxspike"],
    "finesseFaults": lambda p: p["finesse_faults"],
    "finessePerfect": lambda p: p["finesse_perfect"],
}
INT_FIELDS = list(PY.keys())
ROUNDS = [(mi, ri) for mi, m in enumerate(MS) for ri in range(len(m["rounds"]))]
ALLPP = [(mi, ri, pl) for (mi, ri) in ROUNDS for pl in ("yachi", "pinglamb")]


def pobj(mi, ri, pl):
    return MS[mi]["rounds"][ri]["players"][pl]


# =====================================================================
# Facts.dfy — flat scalar consts
# =====================================================================

def emit_facts():
    L = []
    L.append("// Facts.dfy — GENERATED by codegen_dafny.py from facts.json. DO NOT EDIT.")
    L.append("// Flat named scalar consts, one per datum referenced by the 54 claims.")
    L.append("// Every literal is emitted from facts.json (no hand-typed data).")
    L.append("// Naming: m{match_idx0}_r{round_idx0}_{player}_{field}. Winner/score/")
    L.append("// round-count as m{mi}_winner / m{mi}_scoreYachi / m{mi}_scorePinglamb /")
    L.append("// m{mi}_nrounds / m{mi}_r{ri}_winner. yachi garbage_events amt as")
    L.append("// m{mi}_r{ri}_yachi_ge{k} (only R019 reads them; pinglamb ge omitted).")
    L.append("// Omitted from facts.json (no claim references): garbagesent, kills,")
    L.append("// inputs, leaderboard block, per-match ts, garbage_events.frame,")
    L.append("// clears singles/doubles/triples/tspin_singles/mini_*.")
    L.append("")
    L.append(f"const nmatches: int := {len(MS)}")
    for mi, m in enumerate(MS):
        L.append(f'const m{mi}_winner: string := "{m["winner"]}"')
        L.append(f"const m{mi}_scoreYachi: int := {m['score']['yachi']}")
        L.append(f"const m{mi}_scorePinglamb: int := {m['score']['pinglamb']}")
        L.append(f"const m{mi}_nrounds: int := {len(m['rounds'])}")
        for ri, r in enumerate(m["rounds"]):
            L.append(f'const m{mi}_r{ri}_winner: string := "{r["winner"]}"')
            for pl in ("yachi", "pinglamb"):
                p = r["players"][pl]
                for f in INT_FIELDS:
                    L.append(f"const m{mi}_r{ri}_{pl}_{f}: int := {PY[f](p)}")
                L.append(f"const m{mi}_r{ri}_{pl}_alive: bool := {'true' if p['alive'] else 'false'}")
            for k, e in enumerate(r["players"]["yachi"]["garbage_events"]):
                L.append(f"const m{mi}_r{ri}_yachi_ge{k}: int := {e['amt']}")
    L.append("")
    return "\n".join(L)


# =====================================================================
# Dafny expression primitives over the flat consts
# =====================================================================

def S(mi, ri, pl, field):
    return f"m{mi}_r{ri}_{pl}_{field}"


def WR(mi, ri):
    return f"m{mi}_r{ri}_winner"


def WM(mi):
    return f"m{mi}_winner"


def SC(mi, which):
    return f"m{mi}_score{which}"


def NR(mi):
    return f"m{mi}_nrounds"


def wval(mi, ri, field):
    """r['players'][r['winner']][field] — selected by the winner-string const."""
    return (f"(if {WR(mi,ri)} == \"yachi\" then {S(mi,ri,'yachi',field)} "
            f"else {S(mi,ri,'pinglamb',field)})")


def lval(mi, ri, field):
    """the non-winner player's field."""
    return (f"(if {WR(mi,ri)} == \"yachi\" then {S(mi,ri,'pinglamb',field)} "
            f"else {S(mi,ri,'yachi',field)})")


def roundmax_lt(mi, ri):
    """round duration = max of the two players' lifetime."""
    y, p = S(mi, ri, "yachi", "lifetime"), S(mi, ri, "pinglamb", "lifetime")
    return f"(if {y} >= {p} then {y} else {p})"


def bal(op, terms):
    """Balanced (log-depth) associative fold. Deep LEFT-nested chains overflow
    Boogie's recursive AST visitor (stack overflow); a balanced tree keeps depth
    at O(log n) so 1000+-term ground sums/conjunctions verify safely."""
    terms = list(terms)
    if len(terms) == 1:
        return terms[0]
    mid = len(terms) // 2
    return f"({bal(op, terms[:mid])} {op} {bal(op, terms[mid:])})"


def sum_field(pl, field, scope=None):
    scope = scope or ROUNDS
    terms = [S(mi, ri, pl, field) for (mi, ri) in scope]
    val = sum(PY[field](pobj(mi, ri, pl)) for (mi, ri) in scope)
    return bal("+", terms), val


def sum_sq_field(pl, field):
    terms = [f"({S(mi,ri,pl,field)} * {S(mi,ri,pl,field)})" for (mi, ri) in ROUNDS]
    val = sum(PY[field](pobj(mi, ri, pl)) ** 2 for (mi, ri) in ROUNDS)
    return bal("+", terms), val


def sum_field_pp(field):
    terms = [S(mi, ri, pl, field) for (mi, ri, pl) in ALLPP]
    val = sum(PY[field](pobj(mi, ri, pl)) for (mi, ri, pl) in ALLPP)
    return bal("+", terms), val


def count_expr(conds):
    terms = [f"(if {c} then 1 else 0)" for c, _ in conds]
    val = sum(1 for _, b in conds if b)
    return bal("+", terms), val


def all_le(field, scope_pp, V):
    return bal("&&", [f"{S(mi,ri,pl,field)} <= {V}" for (mi, ri, pl) in scope_pp])


def all_ge(field, scope_pp, V):
    return bal("&&", [f"{S(mi,ri,pl,field)} >= {V}" for (mi, ri, pl) in scope_pp])


def max_is(field, V, scope_pp, achieve):
    ai, ari, apl = achieve
    return f"({S(ai,ari,apl,field)} == {V}) && ({all_le(field, scope_pp, V)})"


def eq(a, b):
    return f"({a} == {b})"


def andjoin(parts):
    return bal("&&", [f"({p})" for p in parts])


# =====================================================================
# Per-claim ensures builders (faithful translations of the python_check)
# =====================================================================

def build_C001():
    ye, yv = count_expr([(f'{WM(i)} == "yachi"', MS[i]["winner"] == "yachi") for i in range(10)])
    pe, pv = count_expr([(f'{WM(i)} == "pinglamb"', MS[i]["winner"] == "pinglamb") for i in range(10)])
    return andjoin([eq(ye, yv), f"{yv} == 6", eq(pe, pv), f"{pv} == 4"])


def build_C002():
    tot = sum(len(m["rounds"]) for m in MS)
    totexpr = bal("+", [NR(i) for i in range(10)])
    ye, yv = count_expr([(f'{WR(mi,ri)} == "yachi"', MS[mi]["rounds"][ri]["winner"] == "yachi") for (mi, ri) in ROUNDS])
    pe, pv = count_expr([(f'{WR(mi,ri)} == "pinglamb"', MS[mi]["rounds"][ri]["winner"] == "pinglamb") for (mi, ri) in ROUNDS])
    return andjoin([f"({totexpr}) == {tot}", f"{tot} == 79", eq(ye, yv), f"{yv} == 43", eq(pe, pv), f"{pv} == 36"])


def build_R002():
    ye, yv = count_expr([(f'{WR(mi,ri)} == "yachi"', MS[mi]["rounds"][ri]["winner"] == "yachi") for (mi, ri) in ROUNDS])
    pe, pv = count_expr([(f'{WR(mi,ri)} == "pinglamb"', MS[mi]["rounds"][ri]["winner"] == "pinglamb") for (mi, ri) in ROUNDS])
    return andjoin([eq(ye, yv), f"{yv} == 43", eq(pe, pv), f"{pv} == 36"])


def build_C003():
    parts = []
    for idx, (sy, sp, w) in [(2, (4, 5, "pinglamb")), (3, (4, 5, "pinglamb")), (10, (5, 4, "yachi"))]:
        ai = idx - 1
        parts += [f"{SC(ai,'Yachi')} == {sy}", f"{SC(ai,'Pinglamb')} == {sp}", f'{WM(ai)} == "{w}"']
    return andjoin(parts)


def winners_seq_eq(mi):
    m = MS[mi]
    parts = [f"{NR(mi)} == {len(m['rounds'])}"]
    for ri, r in enumerate(m["rounds"]):
        parts.append(f'{WR(mi,ri)} == "{r["winner"]}"')
    return parts


def build_C004():
    return andjoin(winners_seq_eq(9))


def build_C005():
    r = 8
    return andjoin([
        f"135000 <= {S(9,r,'yachi','vs')} && {S(9,r,'yachi','vs')} < 136000",
        f"93000 <= {S(9,r,'pinglamb','vs')} && {S(9,r,'pinglamb','vs')} < 94000",
        f'{WR(9,r)} == "yachi"',
        f"{S(9,r,'yachi','apm')} / 1000 == 74",
        f"{S(9,r,'pinglamb','apm')} / 1000 == 43",
    ])


def build_C006():
    V = 228310
    le = " && ".join(f"{roundmax_lt(mi,ri)} <= {V}" for (mi, ri) in ROUNDS)
    mx = roundmax_lt(1, 2)
    return andjoin([
        f"({mx} == {V}) && ({le})",
        f"228000 <= {mx} && {mx} < 229000",
        f'{WR(1,2)} == "yachi"',
    ])


def build_C007():
    return andjoin([
        f"{S(1,2,'yachi','garbagereceived')} == 127",
        f"{S(1,2,'pinglamb','garbagereceived')} == 109",
        f"{S(1,2,'yachi','lines')} == 204",
        f'{WR(1,2)} == "yachi"',
    ])


def build_C008():
    # min over rounds of (round duration = max of the two lifetimes) == 15054
    V = 15054
    ge = " && ".join(f"{roundmax_lt(mi,ri)} >= {V}" for (mi, ri) in ROUNDS)
    mx = roundmax_lt(5, 1)
    return andjoin([
        f"({mx} == {V}) && ({ge})",
        f'{WR(5,1)} == "yachi"',
        f"93000 <= {S(5,1,'yachi','apm')} && {S(5,1,'yachi','apm')} < 94000",
        f"24000 <= {S(5,1,'pinglamb','apm')} && {S(5,1,'pinglamb','apm')} < 25000",
    ])


def build_C009():
    V = 114223
    mx = roundmax_lt(6, 1)
    return andjoin([
        max_is("apm", V, ALLPP, (6, 1, "pinglamb")),
        f"{S(6,1,'pinglamb','apm')} == {V}",
        f"1838 == {S(6,1,'pinglamb','pps')}",
        f'{WR(6,1)} == "pinglamb"',
        f"15000 <= {mx} && {mx} < 16000",
    ])


def build_C010():
    V = 262582
    return andjoin([
        max_is("vs", V, ALLPP, (6, 1, "pinglamb")),
        f"{S(6,1,'pinglamb','vs')} == {V}",
        "262000 <= 262582 && 262582 < 263000",
    ])


def build_C011():
    return andjoin([
        f'{WR(1,8)} == "pinglamb"',
        f"128000 <= {S(1,8,'pinglamb','lifetime')} && {S(1,8,'pinglamb','lifetime')} < 129000",
        f"{S(1,8,'pinglamb','lines')} == 121",
        f"60000 <= {S(1,8,'pinglamb','apm')} && {S(1,8,'pinglamb','apm')} < 61000",
    ])


def build_C012():
    return andjoin([
        f'{WR(2,8)} == "pinglamb"',
        f"30000 <= {S(2,8,'pinglamb','lifetime')} && {S(2,8,'pinglamb','lifetime')} < 31000",
        f"74000 <= {S(2,8,'pinglamb','apm')} && {S(2,8,'pinglamb','apm')} < 75000",
        f"150000 <= {S(2,8,'pinglamb','vs')} && {S(2,8,'pinglamb','vs')} < 151000",
    ])


def build_C013():
    V = 16
    ce, cv = count_expr([(f"{S(mi,ri,pl,'maxspike')} == {V}", pobj(mi, ri, pl)["maxspike"] == V) for (mi, ri, pl) in ALLPP])
    return andjoin([
        max_is("maxspike", V, ALLPP, (3, 2, "yachi")),
        eq(ce, cv), f"{cv} == 3",
        f"{S(3,2,'yachi','maxspike')} == {V}",
        f'{WR(3,2)} == "yachi"',
    ])


def build_C014():
    V = max(abs(m["score"]["yachi"] - m["score"]["pinglamb"]) for m in MS)
    diffs = [f"(if {SC(i,'Yachi')} - {SC(i,'Pinglamb')} >= 0 then {SC(i,'Yachi')} - {SC(i,'Pinglamb')} else {SC(i,'Pinglamb')} - {SC(i,'Yachi')})" for i in range(10)]
    le = bal("&&", [f"{d} <= {V}" for d in diffs])
    return andjoin([
        f"({diffs[5]} == {V}) && ({le})",
        f"{SC(5,'Yachi')} == 5 && {SC(5,'Pinglamb')} == 1",
    ])


def build_C015():
    return andjoin([f"{wval(mi,ri,'vs')} > {lval(mi,ri,'vs')}" for (mi, ri) in ROUNDS])


def build_C016():
    conds = []
    for (mi, ri) in ROUNDS:
        w = MS[mi]["rounds"][ri]["winner"]
        o = "pinglamb" if w == "yachi" else "yachi"
        b = pobj(mi, ri, w)["garbagereceived"] > pobj(mi, ri, o)["garbagereceived"]
        conds.append((f"{wval(mi,ri,'garbagereceived')} > {lval(mi,ri,'garbagereceived')}", b))
    ce, cv = count_expr(conds)
    return andjoin([eq(ce, cv), f"{cv} == 8"])


def build_C017():
    V = 1
    ge = " && ".join(f"{wval(mi,ri,'garbagereceived')} >= {V}" for (mi, ri) in ROUNDS)
    achieve = f"{wval(0,2,'garbagereceived')} == {V}"
    return andjoin([
        f"({achieve}) && ({ge})",
        f"{S(0,2,'pinglamb','garbagereceived')} == 1",
        f'{WR(0,2)} == "pinglamb"',
        f"5000 <= {S(0,2,'yachi','apm')} && {S(0,2,'yachi','apm')} < 6000",
        f"8000 <= {S(0,2,'yachi','vs')} && {S(0,2,'yachi','vs')} < 9000",
    ])


def build_C018():
    V = 21
    return andjoin([
        max_is("tspins", V, ALLPP, (1, 7, "pinglamb")),
        f"{S(1,7,'pinglamb','tspins')} == {V}",
        f'{WR(1,7)} == "pinglamb"',
        f"200000 <= {S(1,7,'pinglamb','lifetime')} && {S(1,7,'pinglamb','lifetime')} < 201000",
    ])


def build_C019():
    V = 10
    return andjoin([
        max_is("topbtb", V, ALLPP, (8, 5, "pinglamb")),
        f"{S(8,5,'pinglamb','topbtb')} == {V}",
    ])


def build_C020():
    e, v = sum_field_pp("allclear")
    return andjoin([eq(e, v), f"{v} == 19"])


def build_C021():
    W = [MS[mi]["rounds"][ri]["winner"] for (mi, ri) in ROUNDS]
    n = len(W)
    parts = []
    y5_starts = [s for s in range(n - 4) if all(W[s + k] == "yachi" for k in range(5))]
    p3_starts = [s for s in range(n - 2) if all(W[s + k] == "pinglamb" for k in range(3))]
    y5_exists = bal("||", [bal("&&", [f'{WR(*ROUNDS[s+k])} == "yachi"' for k in range(5)]) for s in y5_starts])
    p3_exists = bal("||", [bal("&&", [f'{WR(*ROUNDS[s+k])} == "pinglamb"' for k in range(3)]) for s in p3_starts])
    y6_none = bal("&&", ["!" + bal("&&", [f'{WR(*ROUNDS[s+k])} == "yachi"' for k in range(6)]) for s in range(n - 5)])
    p4_none = bal("&&", ["!" + bal("&&", [f'{WR(*ROUNDS[s+k])} == "pinglamb"' for k in range(4)]) for s in range(n - 3)])
    parts += [f"({y5_exists})", f"({y6_none})", f"({p3_exists})", f"({p4_none})"]
    # within-match yachi max run == 4: some match has a 4-window, no match has a 5-window
    m4 = None
    for mi, m in enumerate(MS):
        ws = [r["winner"] for r in m["rounds"]]
        for s in range(len(ws) - 3):
            if all(ws[s + k] == "yachi" for k in range(4)):
                m4 = (mi, s); break
        if m4:
            break
    mi4, s4 = m4
    parts.append(bal("&&", [f'{WR(mi4,s4+k)} == "yachi"' for k in range(4)]))
    no5 = []
    for mi, m in enumerate(MS):
        for s in range(len(m["rounds"]) - 4):
            no5.append("!" + bal("&&", [f'{WR(mi,s+k)} == "yachi"' for k in range(5)]))
    if no5:
        parts.append(bal("&&", no5))
    for (mi, ri) in [(0, 3), (0, 4), (0, 5), (0, 6), (1, 0), (4, 6), (4, 7), (5, 0), (5, 1), (5, 2)]:
        parts.append(f'{WR(mi,ri)} == "yachi"')
    parts.append(f'{WM(1)} == "pinglamb"')
    return andjoin(parts)


def build_C022():
    return andjoin(winners_seq_eq(0) + [f"{SC(0,'Yachi')} == 5 && {SC(0,'Pinglamb')} == 2"])


def build_C023n():
    V = 204
    return andjoin([
        max_is("lines", V, ALLPP, (1, 2, "yachi")),
        f"{S(1,2,'yachi','lines')} == {V}",
    ])


def build_C024():
    scope_pp = [(2, ri, pl) for ri in range(len(MS[2]["rounds"])) for pl in ("yachi", "pinglamb")]
    V = PY["vs"](pobj(2, 5, "yachi"))
    return andjoin([
        f"203000 <= {S(2,5,'yachi','vs')} && {S(2,5,'yachi','vs')} < 204000",
        f"{S(2,5,'yachi','vs')} == {V}",
        f"({all_le('vs', scope_pp, V)})",
    ])


def build_C025():
    return andjoin(winners_seq_eq(3) + [f"{SC(3,'Yachi')} == 5 && {SC(3,'Pinglamb')} == 3"])


def build_C026n():
    parts = []
    for i, (sy, sp) in enumerate([(5, 2), (4, 5), (4, 5), (5, 3), (5, 3), (5, 1), (3, 5), (5, 3), (2, 5), (5, 4)]):
        parts.append(f"{SC(i,'Yachi')} == {sy} && {SC(i,'Pinglamb')} == {sp}")
    return andjoin(parts)


def build_C027():
    parts, vals = [], []
    for w in ("yachi", "pinglamb"):
        conds = []
        for (mi, ri) in ROUNDS:
            rw = MS[mi]["rounds"][ri]["winner"]
            o = "pinglamb" if w == "yachi" else "yachi"
            b = (rw == w) and (pobj(mi, ri, w)["garbagereceived"] > pobj(mi, ri, o)["garbagereceived"])
            cond = (f'({WR(mi,ri)} == "{w}") && ({S(mi,ri,w,"garbagereceived")} > {S(mi,ri,o,"garbagereceived")})')
            conds.append((cond, b))
        e, v = count_expr(conds)
        parts.append(eq(e, v)); vals.append(v)
    parts.append(f"{vals[0]} == 6 && {vals[1]} == 2")
    return andjoin(parts)


# ---- Coaching R claims ----

def build_R003():
    tot = sum(len(m["rounds"]) for m in MS)
    totexpr = bal("+", [NR(i) for i in range(10)])
    parts = [f"nmatches == 10", f"({totexpr}) == {tot}", f"{tot} == 79"]
    for i, m in enumerate(MS):
        w = m["winner"]
        assert m["score"][w] == 5
        parts.append(f"{SC(i, 'Yachi' if w == 'yachi' else 'Pinglamb')} == 5")
    return andjoin(parts)


def build_R004():
    ey, vy = sum_field("yachi", "pieces"); ep, vp = sum_field("pinglamb", "pieces")
    return andjoin([eq(ey, vy), f"{vy} == 7546", eq(ep, vp), f"{vp} == 6971"])


def build_R005():
    ey, vy = sum_field("yachi", "pps"); ep, vp = sum_field("pinglamb", "pps")
    return andjoin([f"{ey} / 79 == 1433", f"{vy} / 79 == 1433", f"{ep} / 79 == 1342", f"{vp} / 79 == 1342"])


def build_R006():
    ey, _ = sum_field("yachi", "apm"); ep, _ = sum_field("pinglamb", "apm")
    return f"0 < {ep} - {ey} && {ep} - {ey} < 20000"


def build_R007():
    epa, _ = sum_field("pinglamb", "garbageAttack"); eyp, _ = sum_field("yachi", "pieces")
    eya, _ = sum_field("yachi", "garbageAttack"); epp, _ = sum_field("pinglamb", "pieces")
    return f"{epa} * {eyp} > {eya} * {epp}"


def build_R008():
    ey, vy = sum_field("yachi", "quads"); ep, vp = sum_field("pinglamb", "quads")
    return andjoin([eq(ey, vy), f"{vy} == 373", eq(ep, vp), f"{vp} == 293"])


def build_R009():
    ep, vp = sum_field("pinglamb", "tspinDoubles"); ey, vy = sum_field("yachi", "tspinDoubles")
    return andjoin([eq(ep, vp), f"{vp} == 339", eq(ey, vy), f"{vy} == 292"])


def build_R010():
    ep, vp = sum_field("pinglamb", "tspinTriples"); ey, vy = sum_field("yachi", "tspinTriples")
    return andjoin([eq(ep, vp), f"{vp} == 82", eq(ey, vy), f"{vy} == 53"])


def build_R011():
    ep, vp = sum_field("pinglamb", "tspins"); ey, vy = sum_field("yachi", "tspins")
    return andjoin([eq(ep, vp), f"{vp} == 482", eq(ey, vy), f"{vy} == 406"])


def build_R012():
    ey, vy = sum_field("yachi", "allclear"); ep, vp = sum_field("pinglamb", "allclear")
    return andjoin([eq(ey, vy), f"{vy} == 12", eq(ep, vp), f"{vp} == 7"])


def build_R013():
    scope_p = [(mi, ri, "pinglamb") for (mi, ri) in ROUNDS]
    scope_y = [(mi, ri, "yachi") for (mi, ri) in ROUNDS]
    ap = max(ROUNDS, key=lambda t: pobj(t[0], t[1], "pinglamb")["topbtb"])
    ay = max(ROUNDS, key=lambda t: pobj(t[0], t[1], "yachi")["topbtb"])
    return andjoin([
        max_is("topbtb", 10, scope_p, (ap[0], ap[1], "pinglamb")),
        max_is("topbtb", 8, scope_y, (ay[0], ay[1], "yachi")),
    ])


def build_R014():
    scope_p = [(mi, ri, "pinglamb") for (mi, ri) in ROUNDS]
    scope_y = [(mi, ri, "yachi") for (mi, ri) in ROUNDS]
    ap = max(ROUNDS, key=lambda t: pobj(t[0], t[1], "pinglamb")["topcombo"])
    ay = max(ROUNDS, key=lambda t: pobj(t[0], t[1], "yachi")["topcombo"])
    return andjoin([
        max_is("topcombo", 7, scope_p, (ap[0], ap[1], "pinglamb")),
        max_is("topcombo", 6, scope_y, (ay[0], ay[1], "yachi")),
    ])


def build_R015():
    yf, _ = sum_field("yachi", "finesseFaults"); pp, _ = sum_field("pinglamb", "pieces")
    pf, _ = sum_field("pinglamb", "finesseFaults"); yp, _ = sum_field("yachi", "pieces")
    return f"146 * ({yf} * {pp}) <= 100 * ({pf} * {yp}) && 100 * ({pf} * {yp}) < 148 * ({yf} * {pp})"


def build_R016():
    yfp, _ = sum_field("yachi", "finessePerfect"); pp, _ = sum_field("pinglamb", "pieces")
    pfp, _ = sum_field("pinglamb", "finessePerfect"); yp, _ = sum_field("yachi", "pieces")
    return f"{yfp} * {pp} > {pfp} * {yp}"


def build_R017():
    yh, _ = sum_field("yachi", "holds"); pp, _ = sum_field("pinglamb", "pieces")
    ph, _ = sum_field("pinglamb", "holds"); yp, _ = sum_field("yachi", "pieces")
    return f"{yh} * {pp} > {ph} * {yp}"


def build_R018():
    ey, vy = sum_field("yachi", "garbageCleared"); ep, vp = sum_field("pinglamb", "garbageCleared")
    return andjoin([eq(ey, vy), f"{vy} == 1368", eq(ep, vp), f"{vp} == 1324"])


def build_R019():
    ge_terms = []
    for (mi, ri) in ROUNDS:
        for k in range(len(pobj(mi, ri, "yachi")["garbage_events"])):
            ge_terms.append(f"m{mi}_r{ri}_yachi_ge{k}")
    q = bal("+", ge_terms)
    qv = sum(e["amt"] for (mi, ri) in ROUNDS for e in pobj(mi, ri, "yachi")["garbage_events"])
    rexpr, rv = sum_field("yachi", "garbagereceived")
    return andjoin([
        f"{q} == 3667", f"{qv} == 3667",
        f"{rexpr} == 3127", f"{rv} == 3127",
        f"14 * {qv} <= 100 * ({qv} - {rv}) && 100 * ({qv} - {rv}) < 15 * {qv}",
    ])


def build_R020():
    return andjoin([
        f'{WM(1)} == "pinglamb"', f"{NR(1)} == 9",
        f'{WM(2)} == "pinglamb"', f"{NR(2)} == 9",
        f'{WM(9)} == "yachi"', f"{NR(9)} == 9",
    ])


def build_R021():
    li = len(MS[9]["rounds"]) - 1
    return andjoin([
        f'{WR(9,li)} == "yachi"',
        f"{S(9,li,'yachi','alive')}",
        f"{S(9,li,'yachi','pps')} == 1630",
        f"{S(9,li,'yachi','apm')} == 74105",
        f"{S(9,li,'yachi','pps')} > {S(9,li,'pinglamb','pps')}",
        f"{S(9,li,'yachi','apm')} > {S(9,li,'pinglamb','apm')}",
    ])


def build_R022():
    li = len(MS[2]["rounds"]) - 1
    return andjoin([
        f'{WR(2,li)} == "pinglamb"',
        f"{S(2,li,'pinglamb','pieces')} == 40",
        f"{S(2,li,'yachi','pieces')} == 53",
        f"{S(2,li,'pinglamb','maxspike')} == 13",
        f"{S(2,li,'yachi','maxspike')} == 5",
    ])


def build_R023():
    def cexpr(who, need_win):
        conds = []
        for mi, m in enumerate(MS):
            rs = m["rounds"]
            for i in range(1, len(rs)):
                prev_not = rs[i - 1]["winner"] != who
                if need_win:
                    cond = f'({WR(mi,i-1)} != "{who}") && ({WR(mi,i)} == "{who}")'
                    b = prev_not and rs[i]["winner"] == who
                else:
                    cond = f'{WR(mi,i-1)} != "{who}"'
                    b = prev_not
                conds.append((cond, b))
        return count_expr(conds)
    ywe, ywv = cexpr("yachi", True); yoe, yov = cexpr("yachi", False)
    pwe, pwv = cexpr("pinglamb", True); poe, pov = cexpr("pinglamb", False)
    assert (ywv, yov, pwv, pov) == (18, 32, 19, 37)
    return andjoin([
        eq(ywe, ywv), f"{ywv} == 18",
        eq(yoe, yov), f"{yov} == 32",
        eq(pwe, pwv), f"{pwv} == 19",
        eq(poe, pov), f"{pov} == 37",
        f"{ywv} * {pov} > {pwv} * {yov}",
    ])


def build_R024():
    scope_y = [(mi, ri, "yachi") for (mi, ri) in ROUNDS]
    scope_p = [(mi, ri, "pinglamb") for (mi, ri) in ROUNDS]
    ay = max(ROUNDS, key=lambda t: pobj(t[0], t[1], "yachi")["maxspike"])
    ap = max(ROUNDS, key=lambda t: pobj(t[0], t[1], "pinglamb")["maxspike"])
    return andjoin([
        max_is("maxspike", 16, scope_y, (ay[0], ay[1], "yachi")),
        max_is("maxspike", 16, scope_p, (ap[0], ap[1], "pinglamb")),
    ])


def build_R025():
    ce_p, cv_p = count_expr([(f"{S(mi,ri,'pinglamb','maxspike')} >= 12", pobj(mi, ri, "pinglamb")["maxspike"] >= 12) for (mi, ri) in ROUNDS])
    ce_y, cv_y = count_expr([(f"{S(mi,ri,'yachi','maxspike')} >= 12", pobj(mi, ri, "yachi")["maxspike"] >= 12) for (mi, ri) in ROUNDS])
    return andjoin([eq(ce_p, cv_p), f"{cv_p} == 22", eq(ce_y, cv_y), f"{cv_y} == 16"])


def build_R026():
    ysq, _ = sum_sq_field("yachi", "pps"); ys, _ = sum_field("yachi", "pps")
    psq, _ = sum_sq_field("pinglamb", "pps"); ps, _ = sum_field("pinglamb", "pps")
    return f"79 * {ysq} - {ys} * {ys} < 79 * {psq} - {ps} * {ps}"


def build_R027():
    psq, _ = sum_sq_field("pinglamb", "apm"); ps, _ = sum_field("pinglamb", "apm")
    ysq, _ = sum_sq_field("yachi", "apm"); ys, _ = sum_field("yachi", "apm")
    return f"79 * {psq} - {ps} * {ps} < 79 * {ysq} - {ys} * {ys}"


NARRATIVE_BUILDERS = {
    "C001": build_C001, "C002": build_C002, "C003": build_C003, "C004": build_C004,
    "C005": build_C005, "C006": build_C006, "C007": build_C007, "C008": build_C008,
    "C009": build_C009, "C010": build_C010, "C011": build_C011, "C012": build_C012,
    "C013": build_C013, "C014": build_C014, "C015": build_C015, "C016": build_C016,
    "C017": build_C017, "C018": build_C018, "C019": build_C019, "C020": build_C020,
    "C021": build_C021, "C022": build_C022, "C023": build_C023n, "C024": build_C024,
    "C025": build_C025, "C026": build_C026n, "C027": build_C027,
}
COACHING_BUILDERS = {
    "R001": build_C001, "R002": build_R002, "R003": build_R003, "R004": build_R004,
    "R005": build_R005, "R006": build_R006, "R007": build_R007, "R008": build_R008,
    "R009": build_R009, "R010": build_R010, "R011": build_R011, "R012": build_R012,
    "R013": build_R013, "R014": build_R014, "R015": build_R015, "R016": build_R016,
    "R017": build_R017, "R018": build_R018, "R019": build_R019, "R020": build_R020,
    "R021": build_R021, "R022": build_R022, "R023": build_R023, "R024": build_R024,
    "R025": build_R025, "R026": build_R026, "R027": build_R027,
}


def slug(gloss):
    return re.sub(r"[^a-zA-Z0-9]+", "_", gloss).strip("_").lower()[:60]


def emit_claims(claims_path, builders, module_comment):
    claims = json.load(open(claims_path))
    lines = [f"// {module_comment} — GENERATED by codegen_dafny.py. DO NOT EDIT.",
             'include "Facts.dfy"', ""]
    mapping = []
    for c in claims:
        cid = c["id"]
        ens = builders[cid]()
        name = f"{cid}_{slug(c['english_gloss'])}"
        lines.append(f"// {cid}: {c['english_gloss']}")
        lines.append(f"// python_check: {c['python_check']}")
        lines.append(f"lemma {name}()")
        lines.append(f"  ensures {ens}")
        lines.append("{")
        lines.append("}")
        lines.append("")
        mapping.append({"id": cid, "lemma": name})
    return "\n".join(lines), mapping


def lemma_index():
    """id -> {lemma, file} for all 54 claims. Used by build_proof_map.py so the
    proof map's status column comes from the real verifier, never codegen."""
    _, nmap = emit_claims(os.path.join(HERE, "claims-narrative.json"), NARRATIVE_BUILDERS, "")
    _, cmap = emit_claims(os.path.join(HERE, "claims-coaching.json"), COACHING_BUILDERS, "")
    return ([{"id": m["id"], "lemma": m["lemma"], "file": "dafny/Claims_narrative.dfy"} for m in nmap]
            + [{"id": m["id"], "lemma": m["lemma"], "file": "dafny/Claims_coaching.dfy"} for m in cmap])


def main():
    os.makedirs(OUT, exist_ok=True)
    stale = os.path.join(OUT, "Lib.dfy")  # remove artifact of the old nested design
    if os.path.exists(stale):
        os.remove(stale)
    with open(os.path.join(OUT, "Facts.dfy"), "w") as f:
        f.write(emit_facts())
    nsrc, _ = emit_claims(os.path.join(HERE, "claims-narrative.json"), NARRATIVE_BUILDERS, "Claims_narrative.dfy")
    with open(os.path.join(OUT, "Claims_narrative.dfy"), "w") as f:
        f.write(nsrc)
    csrc, _ = emit_claims(os.path.join(HERE, "claims-coaching.json"), COACHING_BUILDERS, "Claims_coaching.dfy")
    with open(os.path.join(OUT, "Claims_coaching.dfy"), "w") as f:
        f.write(csrc)
    print("generated 54 lemmas -> dafny/*.dfy (proof map is written separately by build_proof_map.py from real verifier results)")


if __name__ == "__main__":
    main()
