"""Emit Dafny from a session's facts.json plus a claim ledger.

    python3 -m pipeline.codegen sessions/2026-07-24/report/facts.json \
        --claims sessions/2026-07-24/report/claims-generated.json \
        --outdir sessions/2026-07-24/report/dafny-generated

Produces Facts.dfy (flat named scalar consts, every literal from facts.json) and
Claims.dfy (one empty-bodied lemma per claim, whose ensures clause is the same spec the
Python predicate came from). No data is hand-typed anywhere.

Two design choices, both learned the hard way:

* flat scalar consts rather than a nested `seq<Match>` datatype — deep-indexing one
  giant literal makes Z3 resolve seq and destructor axioms per reference and does not
  scale; flat literals make every proof plain literal arithmetic and verify in seconds
* balanced expression trees for sums (see spec.bal) — a deep left-nested chain
  overflows Boogie's recursive AST visitor
"""
import argparse
import json
import os
import re
from collections import OrderedDict

from .claims.spec import dafny_suffix, read_field, rounds_of, to_dafny

# Every per-round field the families can reference.
ROUND_FIELDS = [
    "apm_x1000", "pps_x1000", "vs_x1000", "lifetime", "maxspike", "topcombo",
    "topbtb", "tspins", "pieces", "lines", "inputs", "holds", "kills",
    "garbage_attack", "garbage_cleared", "garbagesent", "garbagereceived",
    "finesse_faults", "finesse_perfect", "finesse_combo",
    "score", "combo_power", "btb_power", "finaltime_ms",
    "garbage_sent_raw", "garbage_sent_nomult", "garbage_received_raw", "maxspike_nomult",
    "clears.singles", "clears.doubles", "clears.triples", "clears.quads",
    "clears.pentas", "clears.real_tspins", "clears.mini_tspins",
    "clears.tspin_singles", "clears.tspin_doubles", "clears.tspin_triples",
    "clears.tspin_quads",
    "clears.mini_tspin_singles", "clears.mini_tspin_doubles", "clears.mini_tspin_triples",
    "clears.allclear",
]
LB_FIELDS = ["apm_x1000", "pps_x1000", "vs_x1000", "garbagesent",
             "garbagereceived", "kills"]
# Per-round fields that are strings rather than integers.
STR_ROUND_FIELDS = ["gameoverreason"]


def _cap(pl):
    return pl[:1].upper() + pl[1:]


def referenced_consts(facts, claims):
    """Exactly the const names the claims' ensures clauses mention.

    Facts.dfy emits only these. Emitting the whole dataset leaves dead consts that no
    lemma reads, and a dead const is a mutation that can never be killed — it makes the
    anti-vacuity gate report survivors that mean nothing.
    """
    names = set()
    for c in claims:
        names.update(re.findall(r"\bm\d+_[A-Za-z0-9_]+\b", to_dafny(facts, c["spec"])))
    return names


def emit_facts(facts, keep=None):
    def wanted(name):
        return keep is None or name in keep

    lines = [
        "// Facts.dfy - GENERATED by pipeline/codegen.py from facts.json. DO NOT EDIT.",
        "// Flat named scalar consts: one per datum a claim can reference. Every literal",
        "// comes from facts.json; nothing here is hand-written.",
        "",
    ]
    for mi, m in enumerate(facts["matches"]):
        lines.append("")
        lines.append(f"// ---- match {mi + 1} ({m['file']}) ----")
        emit = OrderedDict()
        emit[f"m{mi}_index"] = str(m["index"])
        emit[f"m{mi}_nrounds"] = str(len(m["rounds"]))
        for pl in facts["players"]:
            emit[f"m{mi}_score{_cap(pl)}"] = str(m["score"][pl])
            for f in LB_FIELDS:
                if f in m["leaderboard"][pl]:
                    emit[f"m{mi}_lb_{pl}_{dafny_suffix(f)}"] = str(m["leaderboard"][pl][f])
        if wanted(f"m{mi}_winner"):
            lines.append(f'const m{mi}_winner: string := "{m["winner"]}"')
        for name, val in emit.items():
            if wanted(name):
                lines.append(f"const {name}: int := {val}")
        for ri, r in enumerate(m["rounds"]):
            if wanted(f"m{mi}_r{ri}_winner"):
                lines.append(f'const m{mi}_r{ri}_winner: string := "{r["winner"]}"')
            for pl in facts["players"]:
                p = r["players"][pl]
                for f in ROUND_FIELDS:
                    try:
                        v = read_field(p, f)
                    except KeyError:
                        continue
                    name = f"m{mi}_r{ri}_{pl}_{dafny_suffix(f)}"
                    if wanted(name):
                        lines.append(f"const {name}: int := {v}")
                for f in STR_ROUND_FIELDS:
                    if f not in p:
                        continue
                    name = f"m{mi}_r{ri}_{pl}_{dafny_suffix(f)}"
                    if wanted(name):
                        lines.append(f'const {name}: string := "{p[f]}"')
                for gi, g in enumerate(p.get("garbage_events", [])):
                    name = f"m{mi}_r{ri}_{pl}_ge{gi}"
                    if wanted(name):
                        lines.append(f"const {name}: int := {g['amt']}")
    return "\n".join(lines) + "\n"


def _lemma_name(claim):
    slug = re.sub(r"[^a-z0-9]+", "_", claim["english_gloss"].lower()).strip("_")[:70]
    return f"{claim['id']}_{slug}".rstrip("_")


def emit_claims(facts, claims):
    lines = [
        "// Claims.dfy - GENERATED by pipeline/codegen.py. DO NOT EDIT.",
        "// One lemma per claim. The ensures clause is rendered from the same spec that",
        "// produced the claim's Python predicate, so the checked and the proved",
        "// statements cannot drift apart. Bodies are empty: every const is a transparent",
        "// literal, so each proof is literal arithmetic.",
        "",
        'include "Facts.dfy"',
        "",
    ]
    for c in claims:
        lines.append(f"// {c['id']} [{c.get('family', '?')}] {c['english_gloss']}")
        lines.append(f"// {c['canto']}")
        lines.append(f"lemma {_lemma_name(c)}()")
        lines.append(f"  ensures {to_dafny(facts, c['spec'])}")
        lines.append("{")
        lines.append("}")
        lines.append("")
    return "\n".join(lines) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("facts")
    ap.add_argument("--claims", required=True)
    ap.add_argument("--outdir", required=True)
    args = ap.parse_args(argv)

    with open(args.facts, encoding="utf-8") as fh:
        facts = json.load(fh)
    with open(args.claims, encoding="utf-8") as fh:
        claims = json.load(fh)
    if not all("spec" in c for c in claims):
        raise SystemExit("every claim needs its spec (regenerate with build_claims.py)")

    os.makedirs(args.outdir, exist_ok=True)
    facts_dfy = os.path.join(args.outdir, "Facts.dfy")
    claims_dfy = os.path.join(args.outdir, "Claims.dfy")
    keep = referenced_consts(facts, claims)
    with open(facts_dfy, "w", encoding="utf-8") as fh:
        fh.write(emit_facts(facts, keep))
    with open(claims_dfy, "w", encoding="utf-8") as fh:
        fh.write(emit_claims(facts, claims))

    nconst = sum(1 for line in open(facts_dfy, encoding="utf-8") if line.startswith("const"))
    print(f"wrote {facts_dfy} ({nconst} consts, all referenced by a lemma, "
          f"over {len(rounds_of(facts))} rounds)")
    print(f"wrote {claims_dfy} ({len(claims)} lemmas)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
