"""Emit SMT-LIB 2.6 from a session's facts.json plus one or more claim ledgers.

    python3 -m pipeline.codegen_smt sessions/2026-07-24/report/facts.json \
        --claims sessions/2026-07-24/report/claims-generated.json \
        --out sessions/2026-07-24/report/claims.smt2

One self-contained `.smt2`: the facts as `define-fun` constants, then one
`(push)/(assert (not claim))/(check-sat)/(pop)` block per claim. Every block must
answer `unsat` — the negation is unsatisfiable, so the claim holds on this data.

Why this exists next to the Dafny backend: the Dafny lemmas have empty bodies and
use no quantifiers, functions or loops, so the proof obligation is ground integer
arithmetic that Dafny hands to Boogie which hands it to Z3. Emitting SMT-LIB
directly skips two layers, runs about two orders of magnitude faster, and — the
actual point — is a **standard format**, so a second, independently implemented
solver can check the same file. That is the extractor-agreement argument applied to
the proof side.

The file is committed and gated for byte-identity like the Dafny output, so it is
also a portable artefact: anyone with any SMT-LIB solver can re-check the claims
without installing this pipeline.
"""
import argparse
import json
import os
import re

from .claims.smt import code, code_table, to_smt
from .claims.spec import rounds_of
from .codegen import (CONST_REF, LB_FIELDS, ROUND_FIELDS, STR_ROUND_FIELDS, _cap,
                      _int_lit, load_ledgers)
from .claims.spec import dafny_suffix, read_field

HEADER = """; claims.smt2 - GENERATED by pipeline/codegen_smt.py. DO NOT EDIT.
; Rendered from the same specs as the Python predicates and the Dafny lemmas
; (pipeline/claims/spec.py, pipeline/claims/smt.py), so all three state the same
; claims about the same data.
;
; Constant names match Facts.dfy exactly, so the two backends can be read side by
; side. Every literal comes from facts.json; nothing here is hand-written.
;
; Strings are encoded as integer codes (legend below), so the file stays inside
; quantifier-free integer arithmetic and any SMT-LIB solver with QF_NIA can read
; it — not only the two with a theory of strings. Only equality is used on them.
;
; Each claim asserts its NEGATION and expects `unsat`. Check with any SMT-LIB
; solver, e.g.:
;     z3 claims.smt2
;     cvc5 claims.smt2
;     yices-smt2 claims.smt2
; Every answer must be `unsat`; a `sat` means the claim is false on this data.
"""


def referenced(facts, claims):
    """Exactly the constants the rendered claims mention."""
    code_table(facts)
    names = set()
    for c in claims:
        names.update(re.findall(CONST_REF, to_smt(facts, c["spec"])))
    return names


def emit_facts(facts, keep):
    lines = []
    if "nmatches" in keep:
        lines.append(f"(define-fun nmatches () Int {len(facts['matches'])})")
    for mi, m in enumerate(facts["matches"]):
        lines.append("")
        lines.append(f"; ---- match {mi + 1} ({m['file']}) ----")
        if f"m{mi}_winner" in keep:
            lines.append(f"(define-fun m{mi}_winner () Int "
                         f"{code(m['winner'])})  ; {m['winner']}")
        ints = [(f"m{mi}_index", m["index"]), (f"m{mi}_nrounds", len(m["rounds"]))]
        for pl in facts["players"]:
            ints.append((f"m{mi}_score{_cap(pl)}", m["score"][pl]))
            for f in LB_FIELDS:
                if f in m["leaderboard"][pl]:
                    ints.append((f"m{mi}_lb_{pl}_{dafny_suffix(f)}",
                                 m["leaderboard"][pl][f]))
        for name, val in ints:
            if name in keep:
                lines.append(f"(define-fun {name} () Int {val})")
        for ri, r in enumerate(m["rounds"]):
            if f"m{mi}_r{ri}_winner" in keep:
                lines.append(f"(define-fun m{mi}_r{ri}_winner () Int "
                             f"{code(r['winner'])})  ; {r['winner']}")
            for pl in facts["players"]:
                p = r["players"][pl]
                for f in ROUND_FIELDS:
                    try:
                        v = read_field(p, f)
                    except KeyError:
                        continue
                    name = f"m{mi}_r{ri}_{pl}_{dafny_suffix(f)}"
                    if name in keep:
                        lines.append(f"(define-fun {name} () Int {_int_lit(v)})")
                for f in STR_ROUND_FIELDS:
                    if f in p:
                        name = f"m{mi}_r{ri}_{pl}_{dafny_suffix(f)}"
                        if name in keep:
                            lines.append(f"(define-fun {name} () Int "
                                         f"{code(p[f])})  ; {p[f]}")
                for gi, g in enumerate(p.get("garbage_events", [])):
                    name = f"m{mi}_r{ri}_{pl}_ge{gi}"
                    if name in keep:
                        lines.append(f"(define-fun {name} () Int {g['amt']})")
    return lines


def emit(facts, claims):
    codes = code_table(facts)
    keep = referenced(facts, claims)
    legend = "\n".join(f"; {v} = {k}" for k, v in
                        sorted(codes.items(), key=lambda kv: kv[1]))
    # QF_NIA, the narrowest logic that fits. Quantifier-free integer arithmetic,
    # NONlinear because the variance identity squares a datum (`(* v v)`) — QF_LIA
    # rejects that outright. Naming a logic (rather than ALL) is what lets solvers
    # without a string theory accept the file, now that names are integer codes.
    lines = [HEADER, "; string codes:", legend, "", "(set-logic QF_NIA)"]
    lines += emit_facts(facts, keep)
    lines.append("")
    for c in claims:
        lines.append(f"; {c['id']} [{c.get('family', '?')}] {c['english_gloss']}")
        lines.append(f"; {c['canto']}")
        lines.append("(push 1)")
        lines.append(f'(echo "{c["id"]}")')
        lines.append(f"(assert (not {to_smt(facts, c['spec'])}))")
        lines.append("(check-sat)")
        lines.append("(pop 1)")
        lines.append("")
    return "\n".join(lines) + "\n", len(keep)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("facts")
    ap.add_argument("--claims", required=True, nargs="+",
                    help="one or more ledgers; concatenated in the order given")
    ap.add_argument("--out", required=True)
    args = ap.parse_args(argv)

    with open(args.facts, encoding="utf-8") as fh:
        facts = json.load(fh)
    claims = load_ledgers(args.claims)

    text, nconst = emit(facts, claims)
    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"wrote {args.out} ({len(claims)} claims, {nconst} constants, "
          f"{len(rounds_of(facts))} rounds, {len(text) / 1024:.0f} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
