/**
 * Emit a per-lock REPLAY TIMELINE for every round of a session, both players — the data an animated
 * replay draws from, and nothing else.
 *
 *   REPLAY_DIR=sessions/2026-10-03 bun pipeline/sim/emit-replay.ts \
 *     --out sessions/2026-10-03/sim/replay-facts.json
 *
 * QUARANTINED, for the reason every sim/*.json is: the boards come from ONE engine (the vendored
 * Triangle engine, the same one `runCaseOracle` runs), and the `.ttrm` holds no board snapshot, so no
 * board here is ever checked cell for cell against the game. The artefact carries
 * `report_eligible: false`; whatever draws from it mints no claim ids and carries no ✓ badges.
 *
 * WHY THIS DOES NOT REUSE `runCaseOracle`'s OUTPUT (it reuses its ENGINE SETUP — `TL_DEFAULTS` and
 * `createEngine` — and runs it alongside, see below). Its lock cells are captured on
 * `falling.lock.pre`, which on a non-clearing lock fires AFTER the engine has already inserted the
 * incoming garbage and shifted the board up, so those cells sit below where the piece really is; it
 * drops `garbage.tank`'s hole column; it counts no holds; and it passes the wall clock as the engine's
 * date. Changing it would move every committed forecast/opener artefact, so this file reads the engine
 * directly instead and leaves that module's behaviour alone:
 *
 *   - a piece's cells on a non-clearing lock are read off `eng.board.state` AFTER the lock, by cell
 *     IDENTITY (the engine's cell objects survive its own row splices), so they are where the piece is;
 *     on a clearing lock no garbage is inserted and the pre-clear cells are exact;
 *   - every `insertGarbage` call made during a lock is recorded against THAT lock, with its column, by
 *     wrapping this engine instance's own board — never the shared module;
 *   - the engine gets the replay file's own `ts` as its date, not `new Date()`;
 *   - every round is ticked to `replay.frames`, and the ENDING is `results.gameoverreason`, never the
 *     engine's own topout (which `tick()` never reports). The engine's topout is still RECORDED per
 *     player-round as `engine_knockout` ({agrees, lock}) so a viewer can flag the rounds where the
 *     engine's board survives a round the game ended by knock-out, or tops out a player who won.
 *
 * THE ROUND TRIP. `build()` decodes every emitted timeline — after a JSON round trip, from an empty
 * board — with `decodeTimeline`, the same function a consumer uses, and requires the decoded board to
 * equal `eng.board.state` (cell for cell, piece letter included) after EVERY lock. Anything else
 * throws. So the delta encoding is lossless by construction against the engine; what it is NOT is
 * evidence that the engine matches the game — that is what `admission` and `prefix` are for, and
 * neither lifts the quarantine.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createEngine } from './vendor/teto/create-engine.mjs';
import { TL_DEFAULTS } from './oracle-source.ts';
import { loadCases, replayDir, runCaseOracle, verifiedBoundary } from './verified-prefix.ts';

export const WIDTH = 10;
/** Engine board height INCLUDING its 20-row buffer: 20 visible rows + 20 above them. */
export const ROWS = 40;
export const VISIBLE_ROWS = 20;
/** How many queued pieces a viewer shows; `seq` is emitted long enough for this at every lock. */
export const NEXT_SHOWN = 5;

/** Fixed positions of one lock entry. A legend rather than keyed objects because the corpus holds
 *  ~28 000 locks a session at its largest, and keys would roughly double the file. The piece and the
 *  hold box are NOT fields: both follow from `seq` and `held` (see `queueStates`), and a second copy
 *  of a derivable quantity is a second thing that can disagree. `build()` checks the derivation
 *  against what the engine actually spawned and held, at every lock. */
/** gameoverreason values meaning the game knocked this player out, and those meaning it did not. */
export const KNOCKOUT_ENDINGS = new Set(['topout', 'garbagesmash']);
export const SURVIVAL_ENDINGS = new Set(['winner']);

export const LOCK_FIELDS = ['dframe', 'place', 'lines', 'spin', 'garbage', 'held', 'attack', 'sent'] as const;
const SPIN_CODE: Record<string, number> = { none: 0, mini: 1, normal: 2, full: 2 };

export type Lock = [number, number | number[], number, number, [number, number][], number, number, number];

/**
 * Every orientation of every piece as cell offsets [dx, dy] from its bounding box's bottom-left,
 * y-UP, cells sorted by (dy, dx). Generated by rotating one drawing per piece and dropping repeats,
 * so a consumer needs no rotation system: `place` names an entry here and an anchor. The engine's
 * own rotation states are not used — a placement is identified by the cells it occupies, which is
 * what the board shows. A shape the engine produces that is missing here throws in `encodePlace`.
 */
export const SHAPES: Record<string, [number, number][][]> = (() => {
  const base: Record<string, [number, number][]> = {
    I: [[0, 0], [1, 0], [2, 0], [3, 0]], O: [[0, 0], [1, 0], [0, 1], [1, 1]],
    T: [[0, 0], [1, 0], [2, 0], [1, 1]], S: [[0, 0], [1, 0], [1, 1], [2, 1]],
    Z: [[1, 0], [2, 0], [0, 1], [1, 1]], J: [[0, 0], [1, 0], [2, 0], [0, 1]],
    L: [[0, 0], [1, 0], [2, 0], [2, 1]],
  };
  const norm = (cs: [number, number][]) => {
    const mx = Math.min(...cs.map(c => c[0])), my = Math.min(...cs.map(c => c[1]));
    return cs.map(([x, y]) => [x - mx, y - my] as [number, number])
      .sort((a, b) => a[1] - b[1] || a[0] - b[0]);
  };
  const out: Record<string, [number, number][][]> = {};
  for (const k of ['I', 'O', 'T', 'S', 'Z', 'J', 'L']) {
    const list: [number, number][][] = [];
    let cur = base[k]!;
    for (let r = 0; r < 4; r++) {
      const n = norm(cur);
      if (!list.some(l => JSON.stringify(l) === JSON.stringify(n))) list.push(n);
      cur = cur.map(([x, y]) => [y, -x] as [number, number]);
    }
    out[k] = list;
  }
  return out;
})();
const CELLS = WIDTH * ROWS;

/** cells (yUp*WIDTH + x) → `place`: shape*CELLS + anchor when all four are on the board, else the
 *  explicit in-range cell list (a piece clipped at the top of the buffer). */
export function encodePlace(piece: string, cells: number[]): number | number[] {
  const sorted = [...cells].sort((a, b) => a - b);
  if (sorted.length !== 4) return sorted;
  const xy = sorted.map(c => [c % WIDTH, Math.floor(c / WIDTH)] as [number, number]);
  const mx = Math.min(...xy.map(c => c[0])), my = Math.min(...xy.map(c => c[1]));
  const key = JSON.stringify(xy.map(([x, y]) => [x - mx, y - my]).sort((a, b) => a[1]! - b[1]! || a[0]! - b[0]!));
  const k = SHAPES[piece]!.findIndex(s => JSON.stringify(s) === key);
  if (k === -1) throw new Error(`no ${piece} shape for cells ${sorted}`);
  return k * CELLS + my * WIDTH + mx;
}

/** `place` → cell indices. */
export function placeCells(piece: string, place: number | number[]): number[] {
  if (Array.isArray(place)) return place;
  const shape = SHAPES[piece]?.[Math.floor(place / CELLS)];
  if (!shape) throw new Error(`bad place ${place} for ${piece}`);
  const a = place % CELLS, ax = a % WIDTH, ay = Math.floor(a / WIDTH);
  return shape.map(([dx, dy]) => (ay + dy) * WIDTH + ax + dx);
}

/**
 * Hold + next-queue derivation from `seq` and the per-lock `held` flags: the piece each lock placed,
 * the hold box when it locked, and the next NEXT_SHOWN pieces at that moment. Exported because
 * `build()` asserts it reproduces every piece the engine locked and every hold box it showed, so a
 * consumer that uses it inherits that check rather than re-deriving the rule.
 */
export function queueStates(seq: string, locks: Lock[]) {
  let cur = seq[0]!, ptr = 1, hold = '';
  const out: { piece: string; hold: string; next: string }[] = [];
  for (const lk of locks) {
    if (lk[5]) {
      if (hold === '') { hold = cur; cur = seq[ptr++]!; }
      else { const t = hold; hold = cur; cur = t; }
    }
    if (ptr + NEXT_SHOWN > seq.length || cur === undefined) throw new Error('seq too short for the next queue');
    out.push({ piece: cur, hold, next: seq.slice(ptr, ptr + NEXT_SHOWN) });
    cur = seq[ptr++]!;
  }
  return out;
}

/**
 * THE decoder: per-lock deltas → the board after each lock, as a ROWS×WIDTH grid indexed [yUp][x]
 * holding a piece letter, 'G' for garbage, or null. Order inside one lock is fixed and mirrors the
 * engine exactly:
 *   1. insert this lock's garbage at the bottom (each `[column, rows]`, in order) — the engine's own
 *      splice, including its quirk of removing the rows just BELOW the top row, not the top row;
 *   2. place the piece's cells;
 *   3. clear every full row (the engine clears all of them) and add empty rows at the top. The count
 *      must equal the lock's `lines`, or this throws. `onLock` receives the cleared rows as pre-clear
 *      yUp indices, for a viewer that flashes them.
 * Garbage and clears never occur on the same lock (the engine inserts garbage only when nothing
 * cleared); `build()` asserts it.
 */
export function decodeTimeline(seq: string, locks: Lock[],
                               onLock?: (board: (string | null)[][], i: number, cleared: number[]) => void) {
  const q = queueStates(seq, locks);
  const b = emptyBoard();
  locks.forEach((lk, i) => { const cleared = applyLock(b, lk, q[i]!.piece); onLock?.(b, i, cleared); });
  return b;
}

export const emptyBoard = (): (string | null)[][] =>
  Array.from({ length: ROWS }, () => new Array<string | null>(WIDTH).fill(null));

/** One lock of `decodeTimeline`, in place; returns the cleared rows (pre-clear yUp, ascending). */
export function applyLock(b: (string | null)[][], lk: Lock, piece: string): number[] {
  const [, place, lines, , garbage] = lk;
  for (const [column, amount] of garbage) {
    const rows = Array.from({ length: amount }, () => {
      const r = new Array<string | null>(WIDTH).fill('G'); r[column] = null; return r;
    });
    b.splice(0, 0, ...rows);
    b.splice(ROWS - amount - 1, amount);
  }
  for (const c of placeCells(piece, place)) b[Math.floor(c / WIDTH)]![c % WIDTH] = piece;
  const cleared: number[] = [];
  for (let y = 0; y < ROWS; y++) if (b[y]!.every(v => v != null)) cleared.push(y);
  if (cleared.length !== lines) throw new Error(`decoder found ${cleared.length} full rows, lock says ${lines}`);
  for (let k = cleared.length - 1; k >= 0; k--) { b.splice(cleared[k]!, 1); b.push(new Array(WIDTH).fill(null)); }
  return cleared;
}

const gridKey = (g: (string | null)[][]) =>
  g.map(r => r.map(c => (c == null ? '.' : c)).join('')).join('/');
const engineKey = (st: any[][]) =>
  st.map(r => r.map((t: any) => (t == null ? '.' : t.mino === 'gb' ? 'G' : String(t.mino).toUpperCase())).join('')).join('/');

/** facts.json's names for the T-spin clear kinds it carries. The engine's (spin, lines) → this key;
 *  a T-spin clear with no key here (a mini quad) counts as `unclassified` and fails admission. */
const FACTS_TSPIN_KINDS = [
  { spin: 2, lines: 1, key: 'tspin_singles' }, { spin: 2, lines: 2, key: 'tspin_doubles' },
  { spin: 2, lines: 3, key: 'tspin_triples' }, { spin: 2, lines: 4, key: 'tspin_quads' },
  { spin: 1, lines: 1, key: 'mini_tspin_singles' }, { spin: 1, lines: 2, key: 'mini_tspin_doubles' },
  { spin: 1, lines: 3, key: 'mini_tspin_triples' },
] as const;

const num = (v: unknown, what: string): number => {
  if (typeof v !== 'number') throw new Error(`facts.json: ${what} is missing or not a number`);
  return v;
};

/** One player's half of one round, through the engine. */
export function runPlayer(player: any, roundPlayers: any[], date: Date) {
  const o = player.replay.options;
  const players = roundPlayers.map((p: any) => ({ gameid: p.replay.options.gameid, userid: p.id, username: p.username }));
  const eng: any = createEngine({ ...TL_DEFAULTS, ...o, g: o.g ?? TL_DEFAULTS.g }, o.gameid, players, date);

  // piece sequence: the first piece spawns inside the constructor, before any hook exists
  const seq: string[] = [];
  let drawn = 0;
  const syncSeq = () => { eng.queue.forEach((p: any, k: number) => { seq[drawn + k] = String(p).toUpperCase(); }); };
  if (!eng.falling) throw new Error('engine constructed without a falling piece');
  seq[0] = String(eng.falling.symbol).toUpperCase(); drawn = 1; syncSeq();
  const origNext = eng.nextPiece.bind(eng);
  eng.nextPiece = (...a: any[]) => { drawn++; const r = origNext(...a); syncSeq(); return r; };

  // garbage, attributed to the lock it is inserted during
  let pendingGarbage: [number, number][] = [];
  const board = eng.board;
  const origInsert = board.insertGarbage.bind(board);
  board.insertGarbage = (g: any) => {
    if (g.size !== 1 || g.bombs) throw new Error(`unsupported garbage shape size=${g.size} bombs=${g.bombs}`);
    pendingGarbage.push([g.column, g.amount]);
    return origInsert(g);
  };

  const locks: Lock[] = [];
  const engineStates: string[] = [];
  const seen = new WeakSet<object>();
  const engineQueue: { piece: string; hold: string }[] = [];   // checked against queueStates, not emitted
  let lastFrame = 0, inLock = false, curHeld = 0, nextHeld = 0, holdsTotal = 0, pcs = 0;
  let preCells: number[] = [], holdAtLock = '';
  // index of the first lock on which the ENGINE topped out, or null. Recorded, never acted on: the
  // ending comes from gameoverreason; this exists so a viewer can flag a round where the two disagree.
  let engineTopLock: number | null = null;

  eng.events.on('falling.new', (e: any) => {
    if (!e.isHold) return;
    holdsTotal++;
    // a hold fired while a lock is still being processed (IHS) belongs to the NEXT piece
    if (inLock) nextHeld = 1; else curHeld = 1;
  });
  eng.events.on('falling.lock.pre', () => {
    inLock = true;
    holdAtLock = eng.held == null ? '' : String(eng.held).toUpperCase();
    preCells = eng.falling.absoluteBlocks
      .filter(([x, y]: [number, number]) => x >= 0 && x < WIDTH && y >= 0 && y < ROWS)
      .map(([x, y]: [number, number]) => y * WIDTH + x);
  });
  eng.events.on('falling.lock', (res: any) => {
    const st = eng.board.state;
    const lines = res.lines as number;
    const spin = SPIN_CODE[res.spin];
    if (spin === undefined) throw new Error(`unknown spin ${res.spin}`);
    let cells: number[];
    if (lines > 0) {
      if (pendingGarbage.length) throw new Error('garbage inserted on a clearing lock');
      cells = preCells;   // nothing was inserted, so the pre-clear cells are where the piece went
    } else {
      // garbage may have been inserted under the piece and shifted it: read it off the board
      cells = [];
      for (let y = 0; y < st.length; y++) for (let x = 0; x < WIDTH; x++) {
        const t = st[y][x];
        if (t != null && t.mino !== 'gb' && !seen.has(t)) cells.push(y * WIDTH + x);
      }
    }
    for (const row of st) for (const t of row) if (t != null) seen.add(t);
    const attack = (res.rawGarbage || []).reduce((a: number, b: number) => a + b, 0);
    const sent = (res.garbage || []).reduce((a: number, b: number) => a + b, 0);
    const piece = String(res.mino).toUpperCase();
    if (res.topout && engineTopLock === null) engineTopLock = locks.length;
    locks.push([eng.frame - lastFrame, encodePlace(piece, cells), lines, spin, pendingGarbage, curHeld,
                attack, sent]);
    engineQueue.push({ piece, hold: holdAtLock });
    lastFrame = eng.frame;
    engineStates.push(engineKey(st));
    if (eng.board.perfectClear && lines > 0) pcs++;
    pendingGarbage = []; curHeld = nextHeld; nextHeld = 0; inLock = false;
  });

  const byFrame = new Map<number, any[]>();
  for (const e of player.replay.events) { if (!byFrame.has(e.frame)) byFrame.set(e.frame, []); byFrame.get(e.frame)!.push(e); }
  const maxF = player.replay.frames;
  if (typeof maxF !== 'number') throw new Error('replay.frames missing');
  for (let f = 0; f <= maxF; f++) eng.tick(byFrame.get(f) || []);
  return { locks, engineStates, engineQueue, seq: seq.join(''), drawn, holdsTotal, pcs, engineTopLock,
           garbageCleared: eng.stats.garbage.cleared as number };
}

/** Round trip: the EMITTED timeline (after a JSON round trip), decoded from an empty board with the
 *  round's `seq`, is the engine's board after every lock, and its derived piece and hold box are the
 *  engine's. Throws on the first difference. */
export function assertRoundTrip(where: string, seq: string, run: ReturnType<typeof runPlayer>) {
  const parsed = JSON.parse(JSON.stringify(run.locks)) as Lock[];
  if (parsed.length !== run.engineStates.length) throw new Error(`${where}: lock count drift`);
  queueStates(seq, parsed).forEach((q, i) => {
    const e = run.engineQueue[i]!;
    if (q.piece !== e.piece || q.hold !== e.hold)
      throw new Error(`${where}: lock ${i} derives ${q.piece}/hold ${q.hold}, engine ${e.piece}/hold ${e.hold}`);
  });
  decodeTimeline(seq, parsed, (b, i) => {
    if (gridKey(b) !== run.engineStates[i])
      throw new Error(`${where}: decoded board differs from eng.board.state after lock ${i}`);
  });
}

export function build(dir: string) {
  const session = dir.split('/').filter(Boolean).pop()!;
  const facts = JSON.parse(readFileSync(`${dir}/report/facts.json`, 'utf8'));
  const matchByFile = new Map<string, any>(facts.matches.map((m: any) => [m.file, m]));

  // group the cases (one per player-round) back into rounds, keeping loadCases' order
  const groups = new Map<string, ReturnType<typeof loadCases>>();
  for (const c of loadCases(dir)) {
    const k = `${c.file}\u0000${c.round}`;
    if (!groups.has(k)) groups.set(k, []);
    groups.get(k)!.push(c);
  }
  const dates = new Map<string, Date>();

  const rounds: any[] = [];
  for (const cases of groups.values()) {
    const { file, round } = cases[0]!;
    const m = matchByFile.get(file);
    if (!m) throw new Error(`facts.json has no match for ${file}`);
    const fr = m.rounds.find((r: any) => r.index === round);
    if (!fr) throw new Error(`facts.json has no round ${round} in ${file}`);
    if (!dates.has(file)) {
      const ts = JSON.parse(readFileSync(`${dir}/${file}`, 'utf8')).ts;
      if (typeof ts !== 'string' || Number.isNaN(Date.parse(ts))) throw new Error(`${file}: no usable ts`);
      dates.set(file, new Date(ts));
    }
    let seq = '';
    const runs: [string, ReturnType<typeof runPlayer>][] = [];
    const players = cases.map(c => {
      const where = `${file} r${round} ${c.user}`;
      const run = runPlayer(c.rawPlayer, c.rawRound!, dates.get(file)!);

      // both players share options.seed, so one sequence serves the round; check it rather than assume
      const need = run.seq.slice(0, run.drawn + NEXT_SHOWN);
      if (!(need.startsWith(seq) || seq.startsWith(need))) throw new Error(`${where}: piece sequences differ`);
      if (need.length > seq.length) seq = need;

      // the existing verified-prefix boundary, from the existing oracle run. Its lock stream must be
      // this timeline's lock stream, or the boundary would index into a different round.
      const r = runCaseOracle(c);
      if (r.locks.length !== run.locks.length || r.records.length !== r.locks.length)
        throw new Error(`${where}: oracle has ${r.locks.length} locks, timeline ${run.locks.length}`);
      let fAbs = 0;
      run.locks.forEach((lk, i) => {
        fAbs += lk[0];
        if (r.locks[i]!.frame !== fAbs || r.locks[i]!.piece !== run.engineQueue[i]!.piece)
          throw new Error(`${where}: oracle lock ${i} differs from the timeline`);
      });
      const b = verifiedBoundary(r, c.truth);
      const last = run.locks.length - 1;
      let after: 'end' | 'no_evidence' | 'check_failed', failedAt: number | null = null;
      if (b.stop === 'mismatch') { after = 'check_failed'; failedAt = b.failedRecord; }
      else if (b.realAttacks > b.simAttacks) {
        // the opponent recorded an attack the engine never made: located at the first lock past the
        // gate's own 25-frame tolerance. Never observed in the corpus, so it fails loudly here too.
        after = 'check_failed';
        const missing = c.truth[b.compared]!;
        const k = r.locks.findIndex(lk => lk.frame > missing.frame + 25);
        failedAt = k === -1 ? last : k;
      } else after = b.index === last ? 'end' : 'no_evidence';
      // Attacks the engine made AFTER the last one the opponent's replay recorded. The existing gate
      // stops at the shorter stream, so these are part of the no-evidence tail rather than a failure:
      // they are the round's last attacks, landing around the moment the opponent's game ended, when
      // a receiver that is about to stop recording cannot be expected to record them. Counted, never
      // hidden, so a viewer can flag the tail.
      const unrecorded = Math.max(0, b.simAttacks - b.realAttacks);

      // admission: the engine's whole-round totals against facts.json (twice-extracted)
      const fp = fr.players[c.user];
      if (!fp) throw new Error(`facts.json: no ${c.user} in ${file} r${round}`);
      const simK: Record<string, number> = Object.fromEntries(FACTS_TSPIN_KINDS.map(k => [k.key, 0]));
      let unclassified = 0;
      for (const lk of run.locks) {
        if (lk[3] === 0 || lk[2] === 0) continue;   // spin is only ever set on a T (detectTSpin)
        const kind = FACTS_TSPIN_KINDS.find(k => k.spin === lk[3] && k.lines === lk[2]);
        if (kind) simK[kind.key]!++; else unclassified++;
      }
      const pairs: [string, number, number][] = [
        ['pieces', run.locks.length, num(fp.pieces, 'pieces')],
        ['lines', run.locks.reduce((a, lk) => a + lk[2], 0), num(fp.lines, 'lines')],
        ['holds', run.holdsTotal, num(fp.holds, 'holds')],
        // the two counters the hole COLUMNS move: a wrong hole changes which garbage rows get cleared
        ['garbage_cleared', run.garbageCleared, num(fp.garbage_cleared, 'garbage_cleared')],
        ['garbage_attack', run.locks.reduce((a, lk) => a + lk[6], 0), num(fp.garbage_attack, 'garbage_attack')],
        ['allclear', run.pcs, num(fp.clears?.allclear, 'clears.allclear')],
        ...FACTS_TSPIN_KINDS.map(k => [k.key, simK[k.key]!, num(fp.clears?.[k.key], `clears.${k.key}`)] as [string, number, number]),
        ['tspin_unclassified', unclassified, 0],
      ];
      const diff = Object.fromEntries(pairs.filter(([, s, f]) => s !== f).map(([k, s, f]) => [k, [s, f]]));

      const gor = c.rawPlayer.replay.results.gameoverreason;
      if (typeof gor !== 'string') throw new Error(`${where}: no gameoverreason`);
      // the game knocked this player out iff it ended them by topout or garbagesmash; anything else
      // (the winner, a forfeit) is a survival. A reason this list does not know throws rather than
      // being read as either.
      if (!KNOCKOUT_ENDINGS.has(gor) && !SURVIVAL_ENDINGS.has(gor)) throw new Error(`${where}: unknown gameoverreason ${gor}`);
      const engineOut = run.engineTopLock !== null;
      runs.push([where, run]);
      return {
        user: c.user,
        frames: c.rawPlayer.replay.frames,
        ending: gor,
        engine_knockout: { agrees: engineOut === KNOCKOUT_ENDINGS.has(gor), lock: run.engineTopLock },
        admission: Object.keys(diff).length ? { ok: false, diff } : { ok: true },
        prefix: { verified_to: b.index, after, failed_at: failedAt, unrecorded_sim_attacks: unrecorded },
        locks: run.locks,
      };
    });
    // the viewer's queue derivation must reproduce what the engine spawned, for both players
    for (const [where, run] of runs) assertRoundTrip(where, seq, run);
    rounds.push({ match: m.index, file, round, seq, players });
  }
  rounds.sort((a, b) => a.match - b.match || a.round - b.round);

  return {
    schema: 'replay-facts/1',
    session,
    report_eligible: false,
    means: 'A per-lock timeline of every round, both players, as the vendored Triangle engine replays '
         + 'the recorded inputs: what an animated replay draws. Boards are SIMULATED — the .ttrm holds '
         + 'no board snapshot, so no board here was ever compared with the game cell for cell.',
    not_eligible_because: [
      'one simulator, no second independent implementation of the boards',
      'the replay file records inputs and attacks, never the board',
    ],
    caveat: {
      garbage_holes: 'Garbage hole columns are the ENGINE\'s seeded-RNG holes. Where `admission.ok` holds they are '
                   + 'consistent with the game\'s own end-of-round counters, garbage cleared and lines '
                   + 'among them, both of which depend on where the holes are; but they are never directly '
                   + 'observed, and they are not the `x` carried by the recorded '
                   + 'garbage events.',
      drop_path: 'Only where each piece ended is recorded here; any path a viewer draws to it is drawn, '
               + 'not the player\'s key inputs.',
      ending: 'The ending of each player-round is results.gameoverreason; the engine\'s own topout is '
            + 'not used. Every round is ticked to replay.frames. engine_knockout records whether the '
            + 'ENGINE\'s board topped out (lock = index of the first lock it did, else null) and whether '
            + 'that agrees with the game ending the player (gameoverreason topout or garbagesmash). '
            + 'Where agrees is false the simulated board may differ from the real one there.',
      admission: 'admission compares the engine\'s WHOLE-ROUND pieces, lines, holds, garbage cleared, '
               + 'attack, all clears and T-spin clear kinds with report/facts.json. Agreement confirms totals only and does not '
               + 'lift the quarantine.',
      prefix: 'prefix is the existing verified-prefix gate (verifiedBoundary, frame+amount+row) over the '
            + 'existing oracle run: locks <= verified_to are on boards whose attacks matched the '
            + 'opponent\'s recorded incoming garbage. after = "no_evidence": the attacks ran out, and '
            + 'later locks are neither confirmed nor refuted; "check_failed": the check failed at lock '
            + 'failed_at; "end": verified to the last lock. unrecorded_sim_attacks counts attacks the '
            + 'engine made after the last one the opponent\'s replay recorded — the gate stops at the '
            + 'shorter stream, so they sit in the no-evidence tail and are counted rather than hidden.',
    },
    board: {
      width: WIDTH, rows: ROWS, visible_rows: VISIBLE_ROWS,
      coords: 'y-UP: row 0 is the bottom row; rows >= visible_rows are the buffer above the field',
      cell: 'yUp * width + x',
      garbage_cell: 'G in a decoded board',
    },
    lock_fields: LOCK_FIELDS,
    lock_legend: {
      dframe: 'engine frames since the previous lock (since frame 0 for the first)',
      place: 'where the piece ended: shape * (width * rows) + anchor, the shape indexing shapes[piece] '
           + 'and the anchor the yUp * width + x of its bounding box\'s bottom-left; an ARRAY of cell '
           + 'indices instead when the piece is clipped at the top of the buffer. On a clearing lock '
           + 'these are the cells before the clear',
      lines: 'lines this lock cleared; the rows are every full row after placing, which '
           + 'decodeTimeline finds and checks against this count',
      spin: '0 none, 1 mini, 2 full',
      garbage: '[hole column, rows] per insertion made during this lock, in order, applied BEFORE '
             + 'the piece is placed (see decodeTimeline)',
      held: '1 if hold was used while this piece was the active one. The piece itself and the hold '
          + 'box are derived from seq and this flag (queueStates)',
      attack: 'lines of attack this lock generated, before cancellation',
      sent: 'what of it was sent after cancelling incoming garbage',
    },
    shapes: SHAPES,
    seq_legend: 'the round\'s piece sequence from options.seed (shared by both players), long enough '
              + 'for hold + next ' + NEXT_SHOWN + ' at every lock; see queueStates',
    rounds,
  };
}

/** Exactly the bytes the artefact holds: pretty metadata, one round per line. */
export const serialise = (data: ReturnType<typeof build>) => {
  const { rounds, ...meta } = data;
  const head = JSON.stringify({ ...meta, rounds: '\u0000ROUNDS\u0000' }, null, 2);
  const body = '[\n' + rounds.map(r => '    ' + JSON.stringify(r)).join(',\n') + '\n  ]';
  return head.replace('"\\u0000ROUNDS\\u0000"', body) + '\n';
};

if (import.meta.main) {
  const argv = process.argv.slice(2);
  const oi = argv.indexOf('--out');
  if (oi === -1 || !argv[oi + 1])
    throw new Error('--out <path> is required, e.g.\n'
      + '  REPLAY_DIR=sessions/2026-10-03 bun pipeline/sim/emit-replay.ts \\\n'
      + '    --out sessions/2026-10-03/sim/replay-facts.json');
  const t0 = performance.now();
  const out = build(replayDir());
  const text = serialise(out);
  writeFileSync(argv[oi + 1]!, text);
  const prs = out.rounds.flatMap(r => r.players);
  const after: Record<string, number> = {};
  for (const p of prs) after[p.prefix.after] = (after[p.prefix.after] ?? 0) + 1;
  console.log(`wrote ${argv[oi + 1]}  (session ${out.session}, ${out.rounds.length} rounds, `
    + `${prs.reduce((a, p) => a + p.locks.length, 0)} locks, ${text.length} bytes, `
    + `${((performance.now() - t0) / 1000).toFixed(1)} s)`);
  console.log(`admission: ${prs.filter(p => p.admission.ok).length}/${prs.length} player-rounds agree`);
  for (const r of out.rounds) for (const p of r.players)
    if (!p.admission.ok) console.log(`  ${r.file} r${r.round} ${p.user} ${JSON.stringify((p.admission as any).diff)}`);
  console.log(`prefix: ${JSON.stringify(after)}`);
}
