// The boards drawn for the seven examples in ForecastExamples.dfy. Rows are top -> bottom, 10 wide.
// '.' empty, 'G' garbage, 'X' anonymous stack, otherwise the tetromino letter that placed it
// ('t' = the T that performs the CLEARING spin in example D, to distinguish it from the tucked T).
export const EXAMPLES = [
  {
    id: 'A', verdict: 'accept',
    title: 'An ordinary triple takes the rows between the overhang and the hole',
    lemma: 'ExampleA_PlainTripleClosesTheGap',
    event: 'Event(j, k, roofAt := 15, floorAt := 21, holeOpenAtJ := true, spinAtK := true)',
    history: 'Step(clearedRows := [17, 18, 19], wasSpin := false, garbageRows := 0)',
    clauses: [true, true, true, true],
    reading: 'both',
    panels: [
      { cap: 'The hole at column 4 is already there, covered, with a four-deep well at column 9. The J is next.',
        rows: ['..........', 'XX....XXX.', 'XX.XXXXXX.', 'XXXXXXXXX.', 'XXXXXXXXX.', 'XXXX.XXXXX', '.XXXXXXXXX'],
        hole: [5, 4], floor: [6, 4] },
      { cap: 'The J lands. Its foot at column 3 hangs over nothing — six rows above the hole.',
        add: 'J',
        rows: ['..JJ......', 'XXJ...XXX.', 'XXJXXXXXX.', 'XXXXXXXXX.', 'XXXXXXXXX.', 'XXXX.XXXXX', '.XXXXXXXXX'],
        roof: [0, 3], hole: [5, 4], floor: [6, 4] },
      { cap: 'A vertical I fills the well. Three rows complete — an ordinary triple, no spin.',
        add: 'I',
        rows: ['..JJ......', 'XXJ...XXXI', 'XXJXXXXXXI', 'XXXXXXXXXI', 'XXXXXXXXXI', 'XXXX.XXXXX', '.XXXXXXXXX'],
        clears: [2, 3, 4], roof: [0, 3], hole: [5, 4], floor: [6, 4] },
      { cap: 'After the triple the overhang has settled two rows above the hole. The slot exists now, and did not before.',
        rows: ['..JJ......', 'XXJ...XXXI', 'XXXX.XXXXX', '.XXXXXXXXX'],
        roof: [0, 3], hole: [2, 4], floor: [3, 4] },
      { cap: 'The T slides under the overhang and rotates. T-Spin Double.',
        add: 'T',
        rows: ['..JJ......', 'XXJTTTXXXI', 'XXXXTXXXXX', '.XXXXXXXXX'],
        clears: [1, 2] },
    ],
  },
  {
    id: 'B', verdict: 'accept-loose',
    title: 'One row, taken by a Single — the reading has to decide',
    lemma: 'ExampleB_ASingleIsEnoughOnlyUnderTheLooseReading',
    event: 'Event(j, k, roofAt := 17, floorAt := 21, holeOpenAtJ := true, spinAtK := true)',
    history: 'Step(clearedRows := [19], wasSpin := false, garbageRows := 0)',
    clauses: [true, true, true, 'partial'],
    reading: 'loose',
    panels: [
      { cap: 'Same hole, but only one row will sit between it and the overhang.',
        rows: ['..........', 'XX....XX..', 'XX.XXXXX..', 'XXXX.XXXXX', '.XXXXXXXXX'],
        hole: [3, 4], floor: [4, 4] },
      { cap: 'The J lands, four rows above the floor.',
        add: 'J',
        rows: ['..JJ......', 'XXJ...XX..', 'XXJXXXXX..', 'XXXX.XXXXX', '.XXXXXXXXX'],
        roof: [0, 3], hole: [3, 4], floor: [4, 4] },
      { cap: 'An O fills columns 8 and 9. One row completes — a Single, no spin.',
        add: 'O',
        rows: ['..JJ......', 'XXJ...XXOO', 'XXJXXXXXOO', 'XXXX.XXXXX', '.XXXXXXXXX'],
        clears: [2], roof: [0, 3], hole: [3, 4], floor: [4, 4] },
      { cap: 'One row removed, and the slot is there.',
        rows: ['..JJ......', 'XXJ...XXOO', 'XXXX.XXXXX', '.XXXXXXXXX'],
        roof: [0, 3], hole: [2, 4], floor: [3, 4] },
      { cap: 'T-Spin Double. Identical outcome to A, off one line instead of three.',
        add: 'T',
        rows: ['..JJ......', 'XXJTTTXXOO', 'XXXXTXXXXX', '.XXXXXXXXX'],
        clears: [1, 2] },
    ],
  },
  {
    id: 'C', verdict: 'reject',
    fails: 2,
    title: 'The floor under the nose had not arrived when the overhang was placed',
    lemma: 'ExampleC_TheFloorArrivedAfterTheRoof',
    event: 'Event(j, k, roofAt := 15, floorAt := 21, holeOpenAtJ := false, spinAtK := true)',
    history: 'Step(clearedRows := [17, 18, 19], wasSpin := false, garbageRows := 0)',
    clauses: [true, false, true, true],
    panels: [
      { cap: 'The J lands its overhang on a solid stack. There is no cavity anywhere beneath it.',
        rows: ['..JJ......', 'XXJ...XXX.', 'XXJXXXXXX.', 'XXXXXXXXX.', 'XXXXXXXXX.'],
        roof: [0, 3] },
      { cap: 'Two rows of garbage rise, the older holed at column 7, the newer at column 4. Only now does the cell the nose will rest on exist.',
        rows: ['..JJ......', 'XXJ...XXX.', 'XXJXXXXXX.', 'XXXXXXXXX.', 'XXXXXXXXX.', 'GGGG.GGGGG', 'GGGGGGG.GG'],
        roof: [0, 3], hole: [5, 4], floor: [6, 4], late: true },
      { cap: 'The I completes three rows. An ordinary triple, exactly as in A.',
        add: 'I',
        rows: ['..JJ......', 'XXJ...XXXI', 'XXJXXXXXXI', 'XXXXXXXXXI', 'XXXXXXXXXI', 'GGGG.GGGGG', 'GGGGGGG.GG'],
        clears: [2, 3, 4], roof: [0, 3], hole: [5, 4], floor: [6, 4] },
      { cap: 'The gap closes and the slot forms, on schedule.',
        rows: ['..JJ......', 'XXJ...XXXI', 'GGGG.GGGGG', 'GGGGGGG.GG'],
        roof: [0, 3], hole: [2, 4], floor: [3, 4] },
      { cap: 'T-Spin Double — but the roof was never laid over anything. The opponent supplied the hole afterwards.',
        add: 'T',
        rows: ['..JJ......', 'XXJTTTXXXI', 'GGGGTGGGGG', 'GGGGGGG.GG'],
        clears: [1, 2] },
    ],
  },
  {
    id: 'D', verdict: 'reject',
    fails: 4,
    title: 'The C-Spin: the clear that lowers the overhang is itself a T-spin',
    lemma: 'ExampleD_TheCSpinLowersItsOwnRoof',
    event: 'Event(j, k, roofAt := 15, floorAt := 21, holeOpenAtJ := true, spinAtK := true)',
    history: 'Step(clearedRows := [17, 18, 19], wasSpin := true, garbageRows := 0)',
    clauses: [true, true, true, false],
    panels: [
      { cap: 'The same overhang six rows above the same hole. The rows between hold a T-Spin Triple well at column 3 — and column 6 of the row under the overhang is still open, which is the only way down to it.',
        rows: ['..JJ......', 'XXJ....XXX', 'XXJ.XXXXXX', 'XXX..XXXXX', 'XXX.XXXXXX', 'XXXX.XXXXX', '.XXXXXXXXX'],
        roof: [0, 3], hole: [5, 4], floor: [6, 4] },
      { cap: 'The first T comes down through column 6, slides left to lie flat across the pocket, and rotates: the last kick drops it two rows into the well. Three rows go — as a T-Spin Triple.',
        add: 't',
        rows: ['..JJ......', 'XXJ....XXX', 'XXJtXXXXXX', 'XXXttXXXXX', 'XXXtXXXXXX', 'XXXX.XXXXX', '.XXXXXXXXX'],
        clears: [2, 3, 4], roof: [0, 3], hole: [5, 4], floor: [6, 4] },
      { cap: 'The overhang settles onto the hole — the gap is closed, and closed by a spin.',
        rows: ['..JJ......', 'XXJ....XXX', 'XXXX.XXXXX', '.XXXXXXXXX'],
        roof: [0, 3], hole: [2, 4], floor: [3, 4] },
      { cap: 'An I seals column 6, straight up so it leaves the approach to the pocket clear. Only now is the row under the overhang complete apart from columns 3-5.',
        add: 'I',
        rows: ['......I...', '......I...', '..JJ..I...', 'XXJ...IXXX', 'XXXX.XXXXX', '.XXXXXXXXX'],
        roof: [2, 3], hole: [4, 4], floor: [5, 4] },
      { cap: 'Second T, T-Spin Double. Triple then Double off one overhang — the opener resolving itself.',
        add: 'T',
        rows: ['......I...', '......I...', '..JJ..I...', 'XXJTTTIXXX', 'XXXXTXXXXX', '.XXXXXXXXX'],
        clears: [3, 4] },
    ],
  },
  {
    id: 'E', verdict: 'reject',
    fails: 3,
    title: 'A line does clear, and garbage does arrive — from outside the pair, so nothing moves',
    lemma: 'ExampleE_AClearAndGarbageBothFromOutside',
    event: 'Event(j, k, roofAt := 16, floorAt := 20, holeOpenAtJ := true, spinAtK := true)',
    history: 'Step(clearedRows := [21], wasSpin := false, garbageRows := 4)',
    clauses: [true, true, false, false],
    panels: [
      { cap: 'A genuine overhang over a genuine hole — but four rows apart, one more than a T-spin slot needs.',
        rows: ['..JJ......', 'XXJ...XXX.', '.XJXXXXXX.', 'XXXX.XXXX.', '.XXXXXXXX.', 'XXXXXXXXX.'],
        roof: [0, 3], hole: [3, 4], floor: [4, 4] },
      { cap: 'An I fills the well. The bottom row completes — an ordinary Single, and the only row it takes lies BELOW the hole.',
        add: 'I',
        rows: ['..JJ......', 'XXJ...XXX.', '.XJXXXXXXI', 'XXXX.XXXXI', '.XXXXXXXXI', 'XXXXXXXXXI'],
        clears: [5], roof: [0, 3], hole: [3, 4], floor: [4, 4] },
      { cap: 'The whole stack drops one row. Overhang and hole drop together — still four apart, still no slot.',
        rows: ['..JJ......', 'XXJ...XXX.', '.XJXXXXXXI', 'XXXX.XXXXI', '.XXXXXXXXI'],
        roof: [0, 3], hole: [3, 4], floor: [4, 4] },
      { cap: 'Four rows of garbage rise. Both cells go up by four. Four apart before, four apart after: a row that is not BETWEEN the pair cannot change the distance between them, whoever put it there.',
        rows: ['..JJ......', 'XXJ...XXX.', '.XJXXXXXXI', 'XXXX.XXXXI', '.XXXXXXXXI',
               'GGGGGGGG.G', 'GGGGGGGG.G', 'GGGGGGGG.G', 'GGGGGGGG.G'],
        roof: [0, 3], hole: [3, 4], floor: [4, 4] },
    ],
  },
  {
    id: 'F', verdict: 'reject',
    fails: 1,
    title: 'The setup was perfect and the T was never spun into it',
    lemma: 'ExampleF_ThePerfectSetupThatWasNeverSpun',
    event: 'Event(j, k, roofAt := 15, floorAt := 21, holeOpenAtJ := true, spinAtK := false)',
    history: 'Step(clearedRows := [17, 18, 19], wasSpin := false, garbageRows := 0)',
    clauses: [false, true, true, true],
    panels: [
      { cap: 'Example A exactly: the J lays its overhang six rows above an open hole.',
        rows: ['..JJ......', 'XXJ...XXX.', 'XXJXXXXXX.', 'XXXXXXXXX.', 'XXXXXXXXX.', 'XXXX.XXXXX', '.XXXXXXXXX'],
        roof: [0, 3], hole: [5, 4], floor: [6, 4] },
      { cap: 'The I completes the three rows between. An ordinary triple, no spin.',
        add: 'I',
        rows: ['..JJ......', 'XXJ...XXXI', 'XXJXXXXXXI', 'XXXXXXXXXI', 'XXXXXXXXXI', 'XXXX.XXXXX', '.XXXXXXXXX'],
        clears: [2, 3, 4], roof: [0, 3], hole: [5, 4], floor: [6, 4] },
      { cap: 'The gap closes and the slot is there. Clauses 2, 3 and 4 have all been satisfied.',
        rows: ['..JJ......', 'XXJ...XXXI', 'XXXX.XXXXX', '.XXXXXXXXX'],
        roof: [0, 3], hole: [2, 4], floor: [3, 4] },
      { cap: 'The T is dropped flat on the stack instead. Nothing clears. A forecast is something a player does, not a shape a board passes through.',
        add: 'T',
        rows: ['.......T..', '..JJ..TTT.', 'XXJ...XXXI', 'XXXX.XXXXX', '.XXXXXXXXX'],
        roof: [1, 3], hole: [3, 4], floor: [4, 4] },
    ],
  },
  {
    id: 'G', verdict: 'reject',
    fails: 3,
    title: 'The slot was already complete when the overhang landed',
    lemma: 'ExampleG_TheSlotWasCompleteWhenTheRoofLanded',
    event: 'Event(j, k, roofAt := 18, floorAt := 21, holeOpenAtJ := true, spinAtK := true)',
    history: 'Step(clearedRows := [], wasSpin := false, garbageRows := 0)',
    clauses: [true, true, false, false],
    panels: [
      { cap: 'The slot is finished apart from its roof: bar row, nose and floor already sit on three consecutive rows.',
        rows: ['..........', 'X.....XXXX', 'XXXX.XXXXX', '.XXXXXXXXX'],
        hole: [2, 4], floor: [3, 4] },
      { cap: 'An S drops its right end straight onto the slot. Nothing in the definition asks which piece this was — the overhang is a cell.',
        add: 'S',
        rows: ['..SS......', 'XSS...XXXX', 'XXXX.XXXXX', '.XXXXXXXXX'],
        roof: [0, 3], hole: [2, 4], floor: [3, 4] },
      { cap: 'T-Spin Double. Nothing was ever removed from between the pair, because nothing was ever between them.',
        add: 'T',
        rows: ['..SS......', 'XSSTTTXXXX', 'XXXXTXXXXX', '.XXXXXXXXX'],
        clears: [1, 2] },
    ],
  },
];

/**
 * The overhang is a CELL with an empty cell under it, not a piece. Forecast.dfy could not depend on
 * which tetromino left it even if it wanted to: `roofAt` is an int, and a filled cell is
 * `Stack(placedBy: int)` — the index of the LOCK that placed it, never the shape.
 *
 * The drawn examples lean on the J because its vertical bar plus foot is the tidiest way to leave a
 * roof two rows above a hole. That is a drafting convenience and nothing more, so here are all seven
 * pieces leaving an overhang on the same little ledge. Each is checked by the same gates as the
 * examples: a real orientation, resting on something, and reachable.
 */
export const OVERHANGS = [
  { piece: 'J', roof: [0, 4], how: 'foot right off a vertical bar',
    base: ['..........', '..........', 'XXX.......', 'XXXXXXXXX.'],
    rows: ['...JJ.....', '...J......', 'XXXJ......', 'XXXXXXXXX.'] },
  { piece: 'L', roof: [0, 3], how: 'foot left off a vertical bar',
    base: ['..........', '..........', 'XXX.......', 'XXXXXXXXX.'],
    rows: ['...LL.....', '....L.....', 'XXX.L.....', 'XXXXXXXXX.'] },
  { piece: 'S', roof: [0, 3], how: 'upper half overhanging its own lower half',
    base: ['..........', '..........', 'XXX.......', 'XXXXXXXXX.'],
    rows: ['..SS......', '.SS.......', 'XXX.......', 'XXXXXXXXX.'] },
  { piece: 'Z', roof: [1, 3], how: 'upper half the other way, off the low side',
    base: ['..........', '..........', 'XXX.......', 'XXXXXXXXX.'],
    rows: ['..........', '...ZZ.....', 'XXX.ZZ....', 'XXXXXXXXX.'] },
  { piece: 'T', roof: [1, 3], how: 'flat across the step, two cells hanging',
    base: ['..........', '..........', 'XXX.......', 'XXXXXXXXX.'],
    rows: ['...T......', '..TTT.....', 'XXX.......', 'XXXXXXXXX.'] },
  { piece: 'I', roof: [1, 3], how: 'flat across the step, three cells hanging',
    base: ['..........', '..........', 'XXX.......', 'XXXXXXXXX.'],
    rows: ['..........', '..IIII....', 'XXX.......', 'XXXXXXXXX.'] },
  { piece: 'O', roof: [1, 3], how: 'half on the step, half off it',
    base: ['..........', '..........', 'XXX.......', 'XXXXXXXXX.'],
    rows: ['..OO......', '..OO......', 'XXX.......', 'XXXXXXXXX.'] },
];
