#!/usr/bin/env python3
"""codegen_dafny.py — trust chain for the full 2026-07-24 report (52 claims).

Reads facts.json + claims-narrative.json (C001-C028) + claims-coaching.json
(R001-R024) and GENERATES all Dafny under ./dafny (Facts.dfy, Claims_narrative.dfy,
Claims_coaching.dfy). Proven design carried over from the 07-22 report:

  * FLAT named scalar consts (no seq/datatype indexing) → literal-arithmetic proofs.
  * BALANCED (log-depth) expression trees for every sum/count/conjunction so deep
    ground folds don't overflow Boogie's recursive AST visitor.
  * ONE empty-body lemma per claim; ensures = faithful translation of python_check.
  * Winner/loser-relative reads select via if/else on the winner-string const.

Data emitted = only fields the 52 claims reference: per-round apm/pps/vs/lifetime/
maxspike/topcombo/tspins/topbtb/pieces/garbageAttack/finesseFaults/kills/holds/
garbagereceived/quads/tspinDoubles/tspinTriples/allclear (+ garbage_events amt for
BOTH players), per-match leaderboard apm/pps/kills, and match winner/score/index/
round-count + per-round winner. Everything else in facts.json is omitted.

Usage: python3 codegen_dafny.py
"""
import json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "dafny")
facts = json.load(open(os.path.join(HERE, "facts.json")))
MS = facts["matches"]

RF = {
    "apm": lambda p: p["apm_x1000"], "pps": lambda p: p["pps_x1000"], "vs": lambda p: p["vs_x1000"],
    "lifetime": lambda p: p["lifetime"], "maxspike": lambda p: p["maxspike"],
    "topcombo": lambda p: p["topcombo"], "tspins": lambda p: p["tspins"], "topbtb": lambda p: p["topbtb"],
    "pieces": lambda p: p["pieces"], "garbageAttack": lambda p: p["garbage_attack"],
    "finesseFaults": lambda p: p["finesse_faults"], "kills": lambda p: p["kills"],
    "holds": lambda p: p["holds"], "garbagereceived": lambda p: p["garbagereceived"],
    "quads": lambda p: p["clears"]["quads"], "tspinDoubles": lambda p: p["clears"]["tspin_doubles"],
    "tspinTriples": lambda p: p["clears"]["tspin_triples"], "allclear": lambda p: p["clears"]["allclear"],
}
LBF = {"apm": lambda e: e["apm_x1000"], "pps": lambda e: e["pps_x1000"], "kills": lambda e: e["kills"]}
RFIELDS = list(RF.keys())
LBFIELDS = list(LBF.keys())
ROUNDS = [(mi, ri) for mi, m in enumerate(MS) for ri in range(len(m["rounds"]))]
ALLPP = [(mi, ri, pl) for (mi, ri) in ROUNDS for pl in ("yachi", "pinglamb")]


def pobj(mi, ri, pl):
    return MS[mi]["rounds"][ri]["players"][pl]


def lbobj(mi, pl):
    return MS[mi]["leaderboard"][pl]


# ---------------- Facts.dfy ----------------

def emit_facts():
    L = ["// Facts.dfy — GENERATED by codegen_dafny.py from facts.json. DO NOT EDIT.",
         "// Flat named scalar consts, one per datum referenced by the 52 claims.",
         "// Every literal is emitted from facts.json (no hand-typed data).",
         "// Per-round fields: " + ", ".join(RFIELDS) + " (+ garbage_events amt for both",
         "// players). Per-match leaderboard: apm/pps/kills. Match winner/score/index/",
         "// nrounds + per-round winner. All other facts.json fields are omitted.", ""]
    L.append(f"const nmatches: int := {len(MS)}")
    for mi, m in enumerate(MS):
        L.append(f"const m{mi}_index: int := {m['index']}")
        L.append(f'const m{mi}_winner: string := "{m["winner"]}"')
        L.append(f"const m{mi}_scoreYachi: int := {m['score']['yachi']}")
        L.append(f"const m{mi}_scorePinglamb: int := {m['score']['pinglamb']}")
        L.append(f"const m{mi}_nrounds: int := {len(m['rounds'])}")
        for pl in ("yachi", "pinglamb"):
            for f in LBFIELDS:
                L.append(f"const m{mi}_lb_{pl}_{f}: int := {LBF[f](lbobj(mi, pl))}")
        for ri, r in enumerate(m["rounds"]):
            L.append(f'const m{mi}_r{ri}_winner: string := "{r["winner"]}"')
            for pl in ("yachi", "pinglamb"):
                p = r["players"][pl]
                for f in RFIELDS:
                    L.append(f"const m{mi}_r{ri}_{pl}_{f}: int := {RF[f](p)}")
                for k, e in enumerate(p["garbage_events"]):
                    L.append(f"const m{mi}_r{ri}_{pl}_ge{k}: int := {e['amt']}")
    L.append("")
    return "\n".join(L)


# ---------------- expression primitives ----------------

def bal(op, terms):
    terms = list(terms)
    if not terms:
        return "0"
    if len(terms) == 1:
        return terms[0]
    mid = len(terms) // 2
    return f"({bal(op, terms[:mid])} {op} {bal(op, terms[mid:])})"


def S(mi, ri, pl, f): return f"m{mi}_r{ri}_{pl}_{f}"
def WR(mi, ri): return f"m{mi}_r{ri}_winner"
def WM(mi): return f"m{mi}_winner"
def SC(mi, w): return f"m{mi}_score{w}"
def NR(mi): return f"m{mi}_nrounds"
def MI(mi): return f"m{mi}_index"
def LB(mi, pl, f): return f"m{mi}_lb_{pl}_{f}"


def wval(mi, ri, f):
    return f'(if {WR(mi,ri)} == "yachi" then {S(mi,ri,"yachi",f)} else {S(mi,ri,"pinglamb",f)})'


def lval(mi, ri, f):
    return f'(if {WR(mi,ri)} == "yachi" then {S(mi,ri,"pinglamb",f)} else {S(mi,ri,"yachi",f)})'


def roundmax_lt(mi, ri):
    y, p = S(mi, ri, "yachi", "lifetime"), S(mi, ri, "pinglamb", "lifetime")
    return f"(if {y} >= {p} then {y} else {p})"


def geSum(mi, ri, pl):
    return bal("+", [f"m{mi}_r{ri}_{pl}_ge{k}" for k in range(len(pobj(mi, ri, pl)["garbage_events"]))])


def sum_rf(pl, f, scope=None):
    scope = scope or ROUNDS
    return bal("+", [S(mi, ri, pl, f) for (mi, ri) in scope]), sum(RF[f](pobj(mi, ri, pl)) for (mi, ri) in scope)


def sumsq_rf(pl, f):
    return (bal("+", [f"({S(mi,ri,pl,f)} * {S(mi,ri,pl,f)})" for (mi, ri) in ROUNDS]),
            sum(RF[f](pobj(mi, ri, pl)) ** 2 for (mi, ri) in ROUNDS))


def count_expr(conds):
    return bal("+", [f"(if {c} then 1 else 0)" for c, _ in conds]), sum(1 for _, b in conds if b)


def eq(a, b): return f"({a} == {b})"
def andjoin(parts): return bal("&&", [f"({p})" for p in parts])


def max_pp_is(field, V, achieve):
    ai, ari, apl = achieve
    return f"({S(ai,ari,apl,field)} == {V}) && ({bal('&&', [f'{S(mi,ri,pl,field)} <= {V}' for (mi,ri,pl) in ALLPP])})"


def max_player_is(pl, field, V, achieve):
    scope = [(mi, ri) for (mi, ri) in ROUNDS]
    ai, ari = achieve
    return f"({S(ai,ari,pl,field)} == {V}) && ({bal('&&', [f'{S(mi,ri,pl,field)} <= {V}' for (mi,ri) in scope])})"


def rmax_is(V, achieve):
    return f"({roundmax_lt(*achieve)} == {V}) && ({bal('&&', [f'{roundmax_lt(mi,ri)} <= {V}' for (mi,ri) in ROUNDS])})"


def rmin_is(V, achieve):
    return f"({roundmax_lt(*achieve)} == {V}) && ({bal('&&', [f'{roundmax_lt(mi,ri)} >= {V}' for (mi,ri) in ROUNDS])})"


def lb_max_is(field, V, achieve):
    ai, apl = achieve
    scope = [(mi, pl) for mi in range(len(MS)) for pl in ("yachi", "pinglamb")]
    return f"({LB(ai,apl,field)} == {V}) && ({bal('&&', [f'{LB(mi,pl,field)} <= {V}' for (mi,pl) in scope])})"


def variance(pl, field):
    sq, _ = sumsq_rf(pl, field)
    s, _ = sum_rf(pl, field)
    return f"(50 * {sq} - {s} * {s})"


# ---------------- narrative builders ----------------

def bC001():
    pe, pv = count_expr([(f'{WM(i)} == "pinglamb"', MS[i]["winner"] == "pinglamb") for i in range(len(MS))])
    ye, yv = count_expr([(f'{WM(i)} == "yachi"', MS[i]["winner"] == "yachi") for i in range(len(MS))])
    return andjoin([eq(pe, pv), f"{pv} == 4", eq(ye, yv), f"{yv} == 3"])


def _round_wins():
    pe, pv = count_expr([(f'{WR(mi,ri)} == "pinglamb"', MS[mi]["rounds"][ri]["winner"] == "pinglamb") for (mi, ri) in ROUNDS])
    ye, yv = count_expr([(f'{WR(mi,ri)} == "yachi"', MS[mi]["rounds"][ri]["winner"] == "yachi") for (mi, ri) in ROUNDS])
    return pe, pv, ye, yv


def bC002():
    pe, pv, ye, yv = _round_wins()
    return andjoin([eq(pe, pv), f"{pv} == 29", eq(ye, yv), f"{yv} == 21"])


def _score(mi, sy, sp, w):
    return [f'{WM(mi)} == "{w}"', f"{SC(mi,'Yachi')} == {sy}", f"{SC(mi,'Pinglamb')} == {sp}"]


def bC003(): return andjoin(_score(0, 0, 5, "pinglamb"))
def bC004(): return andjoin(_score(3, 0, 5, "pinglamb"))


def bC005():
    def sweep(i):
        return f"(({SC(i,'Yachi')} == 0 && {SC(i,'Pinglamb')} == 5) || ({SC(i,'Yachi')} == 5 && {SC(i,'Pinglamb')} == 0))"
    def issweep(i):
        s = MS[i]["score"]; return set(s.values()) == {0, 5}
    ce, cv = count_expr([(sweep(i), issweep(i)) for i in range(len(MS))])
    cpe, cpv = count_expr([(f'{sweep(i)} && {WM(i)} == "pinglamb"', issweep(i) and MS[i]["winner"] == "pinglamb") for i in range(len(MS))])
    return andjoin([eq(ce, cv), f"{cv} == 2", eq(cpe, cpv), f"{cpv} == 2"])


def bC006():
    return andjoin([f'{WR(*ROUNDS[15])} == "yachi"']
                   + [f'{WR(*ROUNDS[16+k])} == "pinglamb"' for k in range(9)]
                   + [f'{WR(*ROUNDS[25])} == "yachi"'])


def bC007():
    return andjoin([max_pp_is("apm", 95498, (4, 1, "pinglamb")),
                    f"{S(4,1,'pinglamb','apm')} == 95498", "95000 <= 95498 && 95498 < 96000"])


def bC008():
    return andjoin([max_pp_is("vs", 178457, (4, 1, "pinglamb")),
                    f"{S(4,1,'pinglamb','vs')} == 178457", "178000 <= 178457 && 178457 < 179000"])


def bC009():
    return andjoin([f'{WR(4,1)} == "pinglamb"', rmin_is(21023, (4, 1)),
                    f"{roundmax_lt(4,1)} == 21023", "21000 <= 21023 && 21023 < 22000"])


def bC010():
    return andjoin([max_pp_is("maxspike", 17, (4, 7, "pinglamb")), f"{S(4,7,'pinglamb','maxspike')} == 17"])


def bC011():
    return andjoin([f'{WR(2,2)} == "yachi"', rmax_is(240131, (2, 2)),
                    f"{roundmax_lt(2,2)} == 240131", "240000 <= 240131 && 240131 < 241000"])


def bC012():
    return andjoin([f"{geSum(2,2,'yachi')} == 177", f"{geSum(2,2,'pinglamb')} == 158"])


def bC013():
    return andjoin([max_pp_is("topcombo", 8, (2, 2, "yachi")), f"{S(2,2,'yachi','topcombo')} == 8"])


def bC014():
    return andjoin([f"{NR(6)} == 9", f"{SC(6,'Yachi')} == 5 && {SC(6,'Pinglamb')} == 4", f'{WM(6)} == "yachi"'])


def bC015():
    ce, cv = count_expr([(f"{NR(i)} == 9", len(MS[i]["rounds"]) == 9) for i in range(len(MS))])
    le = bal("&&", [f"{NR(i)} <= 9" for i in range(len(MS))])
    return andjoin([f"{NR(6)} == 9", f"({NR(6)} == 9) && ({le})", eq(ce, cv), f"{cv} == 1"])


def bC016():
    seq = ["yachi", "yachi", "pinglamb", "pinglamb", "pinglamb", "yachi", "yachi", "pinglamb", "yachi"]
    return andjoin([f"{NR(6)} == 9"] + [f'{WR(6,i)} == "{w}"' for i, w in enumerate(seq)])


def bC017():
    return andjoin([f'{WR(6,7)} == "pinglamb"', f'{WR(6,8)} == "yachi"'])


def bC018():
    return andjoin([max_pp_is("tspins", 18, (1, 2, "pinglamb")), f"{S(1,2,'pinglamb','tspins')} == 18",
                    f'{WR(1,2)} == "yachi"'])


def bC019():
    return andjoin([max_pp_is("topbtb", 8, (5, 4, "pinglamb")), f"{S(5,4,'pinglamb','topbtb')} == 8"])


def bC020():
    return andjoin([lb_max_is("apm", 64901, (3, "pinglamb")), f"{LB(3,'pinglamb','apm')} == 64901",
                    "64000 <= 64901 && 64901 < 65000"])


def bC021():
    pe = bal("+", [LB(i, "pinglamb", "kills") for i in range(len(MS))])
    pv = sum(lbobj(i, "pinglamb")["kills"] for i in range(len(MS)))
    ye = bal("+", [LB(i, "yachi", "kills") for i in range(len(MS))])
    yv = sum(lbobj(i, "yachi")["kills"] for i in range(len(MS)))
    return andjoin([eq(pe, pv), f"{pv} == 29", eq(ye, yv), f"{yv} == 21"])


def bC022():
    ce, cv = count_expr([(f"{LB(i,'yachi','pps')} > {LB(i,'pinglamb','pps')}",
                          lbobj(i, "yachi")["pps_x1000"] > lbobj(i, "pinglamb")["pps_x1000"]) for i in range(len(MS))])
    return andjoin([eq(ce, cv), f"{cv} == 7"])


def bC023(): return andjoin([f'{WM(5)} == "yachi"', f'{WM(6)} == "yachi"'])


def bC024():
    return andjoin([f'{WR(6,8)} == "yachi"', f"{roundmax_lt(6,8)} == 24942", "24000 <= 24942 && 24942 < 25000"])


def bC025(): return andjoin(_score(1, 5, 2, "yachi"))
def bC026(): return andjoin(_score(2, 3, 5, "pinglamb"))
def bC027(): return andjoin(_score(4, 3, 5, "pinglamb"))
def bC028(): return andjoin(_score(5, 5, 3, "yachi"))


# ---------------- coaching builders ----------------

def bR001(): return bC001()


def bR002():
    tot = sum(len(m["rounds"]) for m in MS)
    totexpr = bal("+", [NR(i) for i in range(len(MS))])
    pe, pv, ye, yv = _round_wins()
    return andjoin([f"({totexpr}) == {tot}", f"{tot} == 50", eq(pe, pv), f"{pv} == 29", eq(ye, yv), f"{yv} == 21"])


def bR003():
    ys, _ = sum_rf("yachi", "pps"); ps, _ = sum_rf("pinglamb", "pps")
    return andjoin([f"70000 <= {ys} && {ys} < 70500", f"66500 <= {ps} && {ps} < 67000"])


def bR004():
    pa, _ = sum_rf("pinglamb", "garbageAttack"); yp, _ = sum_rf("yachi", "pieces")
    ya, _ = sum_rf("yachi", "garbageAttack"); pp, _ = sum_rf("pinglamb", "pieces")
    return f"{pa} * {yp} > {ya} * {pp}"


def bR005():
    ye, yv = sum_rf("yachi", "pieces"); pe, pv = sum_rf("pinglamb", "pieces")
    return andjoin([eq(ye, yv), f"{yv} == 4748", eq(pe, pv), f"{pv} == 4439"])


def bR006():
    yf, _ = sum_rf("yachi", "finesseFaults"); pp, _ = sum_rf("pinglamb", "pieces")
    pf, _ = sum_rf("pinglamb", "finesseFaults"); yp, _ = sum_rf("yachi", "pieces")
    return f"{yf} * {pp} < {pf} * {yp}"


def bR007():
    yq, yqv = sum_rf("yachi", "quads"); pq, pqv = sum_rf("pinglamb", "quads")
    yd, ydv = sum_rf("yachi", "tspinDoubles"); pd, pdv = sum_rf("pinglamb", "tspinDoubles")
    return andjoin([eq(yq, yqv), f"{yqv} == 248", eq(pq, pqv), f"{pqv} == 191",
                    eq(yd, ydv), f"{ydv} == 189", eq(pd, pdv), f"{pdv} == 232"])


def bR008():
    pe = bal("+", [f"({S(mi,ri,'pinglamb','tspinDoubles')} + {S(mi,ri,'pinglamb','tspinTriples')})" for (mi, ri) in ROUNDS])
    pv = sum(pobj(mi, ri, "pinglamb")["clears"]["tspin_doubles"] + pobj(mi, ri, "pinglamb")["clears"]["tspin_triples"] for (mi, ri) in ROUNDS)
    ye = bal("+", [f"({S(mi,ri,'yachi','tspinDoubles')} + {S(mi,ri,'yachi','tspinTriples')})" for (mi, ri) in ROUNDS])
    yv = sum(pobj(mi, ri, "yachi")["clears"]["tspin_doubles"] + pobj(mi, ri, "yachi")["clears"]["tspin_triples"] for (mi, ri) in ROUNDS)
    return andjoin([eq(pe, pv), f"{pv} == 284", eq(ye, yv), f"{yv} == 221"])


def bR009():
    pe, pv = sum_rf("pinglamb", "kills"); ye, yv = sum_rf("yachi", "kills")
    return andjoin([eq(pe, pv), f"{pv} == 29", eq(ye, yv), f"{yv} == 21"])


def bR010():
    pe, pv = count_expr([(f'{roundmax_lt(mi,ri)} < 40000 && {WR(mi,ri)} == "pinglamb"',
                          max(pobj(mi, ri, "yachi")["lifetime"], pobj(mi, ri, "pinglamb")["lifetime"]) < 40000 and MS[mi]["rounds"][ri]["winner"] == "pinglamb") for (mi, ri) in ROUNDS])
    ye, yv = count_expr([(f'{roundmax_lt(mi,ri)} < 40000 && {WR(mi,ri)} == "yachi"',
                          max(pobj(mi, ri, "yachi")["lifetime"], pobj(mi, ri, "pinglamb")["lifetime"]) < 40000 and MS[mi]["rounds"][ri]["winner"] == "yachi") for (mi, ri) in ROUNDS])
    return andjoin([eq(pe, pv), f"{pv} == 11", eq(ye, yv), f"{yv} == 5"])


def _pairs():
    return [(mi, i) for mi, m in enumerate(MS) for i in range(len(m["rounds"]) - 1)]


def bR011():
    pairs = _pairs()
    def w(mi, i): return MS[mi]["rounds"][i]["winner"]
    e1, v1 = count_expr([(f'{WR(mi,i)} == "pinglamb" && {WR(mi,i+1)} == "yachi"', w(mi, i) == "pinglamb" and w(mi, i+1) == "yachi") for (mi, i) in pairs])
    e2, v2 = count_expr([(f'{WR(mi,i)} == "pinglamb"', w(mi, i) == "pinglamb") for (mi, i) in pairs])
    e3, v3 = count_expr([(f'{WR(mi,i)} == "yachi" && {WR(mi,i+1)} == "pinglamb"', w(mi, i) == "yachi" and w(mi, i+1) == "pinglamb") for (mi, i) in pairs])
    e4, v4 = count_expr([(f'{WR(mi,i)} == "yachi"', w(mi, i) == "yachi") for (mi, i) in pairs])
    return andjoin([eq(e1, v1), f"{v1} == 8", eq(e2, v2), f"{v2} == 25",
                    eq(e3, v3), f"{v3} == 9", eq(e4, v4), f"{v4} == 18"])


def bR012():
    ya, yav = count_expr([(f"{S(mi,ri,'yachi','apm')} >= 65000", pobj(mi, ri, "yachi")["apm_x1000"] >= 65000) for (mi, ri) in ROUNDS])
    yaw, yawv = count_expr([(f'{S(mi,ri,"yachi","apm")} >= 65000 && {WR(mi,ri)} == "yachi"', pobj(mi, ri, "yachi")["apm_x1000"] >= 65000 and MS[mi]["rounds"][ri]["winner"] == "yachi") for (mi, ri) in ROUNDS])
    pa, pav = count_expr([(f"{S(mi,ri,'pinglamb','apm')} >= 65000", pobj(mi, ri, "pinglamb")["apm_x1000"] >= 65000) for (mi, ri) in ROUNDS])
    paw, pawv = count_expr([(f'{S(mi,ri,"pinglamb","apm")} >= 65000 && {WR(mi,ri)} == "pinglamb"', pobj(mi, ri, "pinglamb")["apm_x1000"] >= 65000 and MS[mi]["rounds"][ri]["winner"] == "pinglamb") for (mi, ri) in ROUNDS])
    return andjoin([eq(ya, yav), f"{yav} == 9", eq(yaw, yawv), f"{yawv} == 8",
                    eq(pa, pav), f"{pav} == 14", eq(paw, pawv), f"{pawv} == 14"])


def bR013():
    ap = max(ROUNDS, key=lambda t: pobj(t[0], t[1], "pinglamb")["maxspike"])
    ay = max(ROUNDS, key=lambda t: pobj(t[0], t[1], "yachi")["maxspike"])
    return andjoin([max_player_is("pinglamb", "maxspike", 17, ap), max_player_is("yachi", "maxspike", 15, ay)])


def bR014():
    pe, pv = count_expr([(f"{S(mi,ri,'pinglamb','maxspike')} >= 12", pobj(mi, ri, "pinglamb")["maxspike"] >= 12) for (mi, ri) in ROUNDS])
    ye, yv = count_expr([(f"{S(mi,ri,'yachi','maxspike')} >= 12", pobj(mi, ri, "yachi")["maxspike"] >= 12) for (mi, ri) in ROUNDS])
    return andjoin([eq(pe, pv), f"{pv} == 13", eq(ye, yv), f"{yv} == 9"])


def bR015():
    # matches with index in (1,4) -> array 0 and 3
    rounds14 = [(mi, ri) for mi in (0, 3) for ri in range(len(MS[mi]["rounds"]))]
    ce, cv = count_expr([(f'{WR(mi,ri)} == "yachi"', MS[mi]["rounds"][ri]["winner"] == "yachi") for (mi, ri) in rounds14])
    return andjoin([f"{MI(0)} == 1 && {SC(0,'Yachi')} == 0 && {SC(0,'Pinglamb')} == 5",
                    f"{MI(3)} == 4 && {SC(3,'Yachi')} == 0 && {SC(3,'Pinglamb')} == 5",
                    eq(ce, cv), f"{cv} == 0"])


def bR016():
    return andjoin([f"{LB(0,'pinglamb','apm')} - {LB(0,'yachi','apm')} >= 12000",
                    f"{LB(3,'pinglamb','apm')} - {LB(3,'yachi','apm')} >= 14000"])


def bR017():
    return andjoin([f'{WM(6)} == "yachi"', f"{SC(6,'Yachi')} == 5 && {SC(6,'Pinglamb')} == 4"])


def bR018():
    rr = range(len(MS[6]["rounds"]))
    ce, cv = count_expr([(f"{S(6,ri,'yachi','apm')} >= 70000", pobj(6, ri, "yachi")["apm_x1000"] >= 70000) for ri in rr])
    cwe, cwv = count_expr([(f'{S(6,ri,"yachi","apm")} >= 70000 && {WR(6,ri)} == "yachi"', pobj(6, ri, "yachi")["apm_x1000"] >= 70000 and MS[6]["rounds"][ri]["winner"] == "yachi") for ri in rr])
    return andjoin([eq(ce, cv), f"{cv} == 3", eq(cwe, cwv), f"{cwv} == 3"])


def bR019(): return f"{variance('yachi','apm')} < {variance('pinglamb','apm')}"
def bR020(): return f"{variance('pinglamb','pps')} < {variance('yachi','pps')}"


def bR021():
    ye, yv = sum_rf("yachi", "allclear"); pe, pv = sum_rf("pinglamb", "allclear")
    return andjoin([eq(ye, yv), f"{yv} == 6", eq(pe, pv), f"{pv} == 4"])


def bR022():
    def geTotal(pl):
        terms = [f"m{mi}_r{ri}_{pl}_ge{k}" for (mi, ri) in ROUNDS for k in range(len(pobj(mi, ri, pl)["garbage_events"]))]
        val = sum(e["amt"] for (mi, ri) in ROUNDS for e in pobj(mi, ri, pl)["garbage_events"])
        return bal("+", terms), val
    yg, ygv = geTotal("yachi"); ygr, ygrv = sum_rf("yachi", "garbagereceived")
    pg, pgv = geTotal("pinglamb"); pgr, pgrv = sum_rf("pinglamb", "garbagereceived")
    return andjoin([f"{yg} - {ygr} == 333", f"{ygv} - {ygrv} == 333",
                    f"{pg} - {pgr} == 329", f"{pgv} - {pgrv} == 329"])


def bR023():
    pe, pv = sum_rf("pinglamb", "tspinTriples"); ye, yv = sum_rf("yachi", "tspinTriples")
    return andjoin([eq(pe, pv), f"{pv} == 52", eq(ye, yv), f"{yv} == 32"])


def bR024():
    ye, yv = sum_rf("yachi", "holds"); pe, pv = sum_rf("pinglamb", "holds")
    return andjoin([eq(ye, yv), f"{yv} == 1792", eq(pe, pv), f"{pv} == 1703"])


NARR = {f"C{n:03d}": globals()[f"bC{n:03d}"] for n in range(1, 29)}
COACH = {f"R{n:03d}": globals()[f"bR{n:03d}"] for n in range(1, 25)}


def slug(g): return re.sub(r"[^a-zA-Z0-9]+", "_", g).strip("_").lower()[:60]


def emit_claims(path, builders, comment):
    claims = json.load(open(path))
    lines = [f"// {comment} — GENERATED by codegen_dafny.py. DO NOT EDIT.", 'include "Facts.dfy"', ""]
    mapping = []
    for c in claims:
        cid = c["id"]
        ens = builders[cid]()
        name = f"{cid}_{slug(c['english_gloss'])}"
        lines += [f"// {cid}: {c['english_gloss']}", f"// python_check: {c['python_check']}",
                  f"lemma {name}()", f"  ensures {ens}", "{", "}", ""]
        mapping.append({"id": cid, "lemma": name})
    return "\n".join(lines), mapping


def lemma_index():
    _, nm = emit_claims(os.path.join(HERE, "claims-narrative.json"), NARR, "")
    _, cm = emit_claims(os.path.join(HERE, "claims-coaching.json"), COACH, "")
    return ([{"id": m["id"], "lemma": m["lemma"], "file": "dafny/Claims_narrative.dfy"} for m in nm]
            + [{"id": m["id"], "lemma": m["lemma"], "file": "dafny/Claims_coaching.dfy"} for m in cm])



CONST_LINE = re.compile(r"^const (\w+)\s*:")


def keep_referenced(facts_src, claims_srcs):
    """Drop consts no lemma reads.

    A const nothing reads is data the proofs do not depend on, so a mutation of it
    can never be killed — it makes the anti-vacuity gate report survivors that mean
    nothing. pipeline/codegen.py filters the generated ledger the same way.
    """
    body = " ".join(claims_srcs)
    out = []
    for line in facts_src.split("\n"):
        m = CONST_LINE.match(line)
        if m and not re.search(rf"\b{m.group(1)}\b", body):
            continue
        out.append(line)
    return "\n".join(out)


def main():
    os.makedirs(OUT, exist_ok=True)
    nsrc, _ = emit_claims(os.path.join(HERE, "claims-narrative.json"), NARR, "Claims_narrative.dfy")
    csrc, _ = emit_claims(os.path.join(HERE, "claims-coaching.json"), COACH, "Claims_coaching.dfy")
    # Facts.dfy is written last, carrying only the consts the lemmas actually read.
    open(os.path.join(OUT, "Facts.dfy"), "w").write(
        keep_referenced(emit_facts(), [nsrc, csrc]))
    open(os.path.join(OUT, "Claims_narrative.dfy"), "w").write(nsrc)
    open(os.path.join(OUT, "Claims_coaching.dfy"), "w").write(csrc)
    print("generated 52 lemmas -> dafny/*.dfy (proof map written by build_proof_map.py from real verifier)")


if __name__ == "__main__":
    main()
