#!/usr/bin/env python3
"""codegen_dafny.py (07-24) — trust chain for the 2026-07-24 session.

Reads facts-24.json + claims-24.json and GENERATES all Dafny source under
./dafny (Facts24.dfy + Claims24.dfy). Same design proven on the 07-22 report:

  * FLAT named scalar consts (no nested datatype / seq indexing) so every proof
    is literal arithmetic — `const m{mi}_r{ri}_{player}_{field}: int := V`.
  * BALANCED (log-depth) expression trees for all sums/conjunctions, so deep
    ground folds don't overflow Boogie's recursive AST visitor.
  * ONE lemma per claim, id-named, ensures = faithful translation of the
    claim's python_check; empty bodies.

Only the fields the 20 claims reference are emitted: lifetime, pieces, vs,
maxspike, clears.allclear — plus garbage_events amt for BOTH players (C018's
comeback differential needs both), match winner/score/index/round-count, and
per-round winner. All other facts.json fields are omitted (documented below).

Usage: python3 codegen_dafny.py   # writes dafny/Facts24.dfy, dafny/Claims24.dfy
"""
import json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "dafny")
facts = json.load(open(os.path.join(HERE, "facts-24.json")))
MS = facts["matches"]

PY = {
    "lifetime": lambda p: p["lifetime"],
    "pieces": lambda p: p["pieces"],
    "vs": lambda p: p["vs_x1000"],
    "maxspike": lambda p: p["maxspike"],
    "allclear": lambda p: p["clears"]["allclear"],
}
INT_FIELDS = list(PY.keys())
ROUNDS = [(mi, ri) for mi, m in enumerate(MS) for ri in range(len(m["rounds"]))]
ALLPP = [(mi, ri, pl) for (mi, ri) in ROUNDS for pl in ("yachi", "pinglamb")]


def pobj(mi, ri, pl):
    return MS[mi]["rounds"][ri]["players"][pl]


# ---------------- Facts24.dfy ----------------

def emit_facts():
    L = ["// Facts24.dfy — GENERATED by codegen_dafny.py from facts-24.json. DO NOT EDIT.",
         "// Flat named scalar consts, one per datum referenced by the 20 claims.",
         "// Every literal is emitted from facts-24.json (no hand-typed data).",
         "// Fields carried: lifetime, pieces, vs, maxspike, allclear (+ garbage_events",
         "// amt for BOTH players, used by C018). Omitted (no claim references them):",
         "// apm/pps/garbagesent/garbagereceived/kills/inputs/holds/topcombo/topbtb/",
         "// tspins/other clears/garbage_attack/garbage_cleared/finesse/leaderboard/ts/",
         "// alive (round winner is carried directly)/garbage_events.frame.", ""]
    L.append(f"const nmatches: int := {len(MS)}")
    for mi, m in enumerate(MS):
        L.append(f"const m{mi}_index: int := {m['index']}")
        L.append(f'const m{mi}_winner: string := "{m["winner"]}"')
        L.append(f"const m{mi}_scoreYachi: int := {m['score']['yachi']}")
        L.append(f"const m{mi}_scorePinglamb: int := {m['score']['pinglamb']}")
        L.append(f"const m{mi}_nrounds: int := {len(m['rounds'])}")
        for ri, r in enumerate(m["rounds"]):
            L.append(f'const m{mi}_r{ri}_winner: string := "{r["winner"]}"')
            for pl in ("yachi", "pinglamb"):
                p = r["players"][pl]
                for f in INT_FIELDS:
                    L.append(f"const m{mi}_r{ri}_{pl}_{f}: int := {PY[f](p)}")
                for k, e in enumerate(p["garbage_events"]):
                    L.append(f"const m{mi}_r{ri}_{pl}_ge{k}: int := {e['amt']}")
    L.append("")
    return "\n".join(L)


# ---------------- expression primitives ----------------

def bal(op, terms):
    terms = list(terms)
    if not terms:
        return "0"
    if len(terms) == 1:
        return terms[0]
    mid = len(terms) // 2
    return f"({bal(op, terms[:mid])} {op} {bal(op, terms[mid:])})"


def S(mi, ri, pl, field):
    return f"m{mi}_r{ri}_{pl}_{field}"


def WR(mi, ri):
    return f"m{mi}_r{ri}_winner"


def WM(mi):
    return f"m{mi}_winner"


def SC(mi, which):
    return f"m{mi}_score{which}"


def NR(mi):
    return f"m{mi}_nrounds"


def MI(mi):
    return f"m{mi}_index"


def wval(mi, ri, field):
    return (f"(if {WR(mi,ri)} == \"yachi\" then {S(mi,ri,'yachi',field)} "
            f"else {S(mi,ri,'pinglamb',field)})")


def lval(mi, ri, field):
    return (f"(if {WR(mi,ri)} == \"yachi\" then {S(mi,ri,'pinglamb',field)} "
            f"else {S(mi,ri,'yachi',field)})")


def roundmax_lt(mi, ri):
    y, p = S(mi, ri, "yachi", "lifetime"), S(mi, ri, "pinglamb", "lifetime")
    return f"(if {y} >= {p} then {y} else {p})"


def geSum(mi, ri, pl):
    terms = [f"m{mi}_r{ri}_{pl}_ge{k}" for k in range(len(pobj(mi, ri, pl)["garbage_events"]))]
    return bal("+", terms)


def wq(mi, ri):
    return f"(if {WR(mi,ri)} == \"pinglamb\" then {geSum(mi,ri,'pinglamb')} else {geSum(mi,ri,'yachi')})"


def lq(mi, ri):
    return f"(if {WR(mi,ri)} == \"pinglamb\" then {geSum(mi,ri,'yachi')} else {geSum(mi,ri,'pinglamb')})"


def sum_field(pl, field, scope=None):
    scope = scope or ROUNDS
    terms = [S(mi, ri, pl, field) for (mi, ri) in scope]
    return bal("+", terms), sum(PY[field](pobj(mi, ri, pl)) for (mi, ri) in scope)


def sum_field_pp(field):
    terms = [S(mi, ri, pl, field) for (mi, ri, pl) in ALLPP]
    return bal("+", terms), sum(PY[field](pobj(mi, ri, pl)) for (mi, ri, pl) in ALLPP)


def count_expr(conds):
    return bal("+", [f"(if {c} then 1 else 0)" for c, _ in conds]), sum(1 for _, b in conds if b)


def eq(a, b):
    return f"({a} == {b})"


def andjoin(parts):
    return bal("&&", [f"({p})" for p in parts])


def rmax_over(scope, V, achieve):
    return f"({roundmax_lt(*achieve)} == {V}) && ({bal('&&', [f'{roundmax_lt(mi,ri)} <= {V}' for (mi,ri) in scope])})"


def rmin_over(scope, V, achieve):
    return f"({roundmax_lt(*achieve)} == {V}) && ({bal('&&', [f'{roundmax_lt(mi,ri)} >= {V}' for (mi,ri) in scope])})"


# ---------------- claim builders ----------------

def build_C001():
    pe, pv = count_expr([(f'{WM(i)} == "pinglamb"', MS[i]["winner"] == "pinglamb") for i in range(len(MS))])
    ye, yv = count_expr([(f'{WM(i)} == "yachi"', MS[i]["winner"] == "yachi") for i in range(len(MS))])
    return andjoin([eq(pe, pv), f"{pv} == 4", eq(ye, yv), f"{yv} == 3"])


def build_C002():
    tot = sum(len(m["rounds"]) for m in MS)
    totexpr = bal("+", [NR(i) for i in range(len(MS))])
    pe, pv = count_expr([(f'{WR(mi,ri)} == "pinglamb"', MS[mi]["rounds"][ri]["winner"] == "pinglamb") for (mi, ri) in ROUNDS])
    ye, yv = count_expr([(f'{WR(mi,ri)} == "yachi"', MS[mi]["rounds"][ri]["winner"] == "yachi") for (mi, ri) in ROUNDS])
    return andjoin([f"({totexpr}) == {tot}", f"{tot} == 50", eq(pe, pv), f"{pv} == 29", eq(ye, yv), f"{yv} == 21"])


def build_C003():
    ep, vp = sum_field("pinglamb", "pieces")
    ey, vy = sum_field("yachi", "pieces")
    return andjoin([eq(ep, vp), f"{vp} == 4439", eq(ey, vy), f"{vy} == 4748"])


def agg_pps_2dp(pl):
    """floor(pieces*100000/ms + 0.5) == (2*P*100000 + M) / (2*M) in Euclidean int div."""
    P, _ = sum_field(pl, "pieces")
    M, _ = sum_field(pl, "lifetime")
    return f"(2 * {P} * 100000 + {M}) / (2 * {M})"


def build_C004():
    return andjoin([f"{agg_pps_2dp('pinglamb')} == 132", f"{agg_pps_2dp('yachi')} == 141"])


def build_C005():
    e, v = sum_field_pp("allclear")
    ep, vp = sum_field("pinglamb", "allclear")
    ey, vy = sum_field("yachi", "allclear")
    return andjoin([eq(e, v), f"{v} == 10", eq(ep, vp), f"{vp} == 4", eq(ey, vy), f"{vy} == 6"])


def build_C006():
    return andjoin([rmin_over(ROUNDS, 21023, (4, 1)), f"{MI(4)} == 5", "20950 <= 21023 && 21023 < 21050"])


def build_C007():
    return andjoin([rmax_over(ROUNDS, 240131, (2, 2)), f"{MI(2)} == 3", "240050 <= 240131 && 240131 < 240150"])


def _per_match_longest(mi, ri, V, winner, lo, hi):
    scope = [(mi, k) for k in range(len(MS[mi]["rounds"]))]
    return andjoin([
        f"{MI(mi)} == {MS[mi]['index']}",
        rmax_over(scope, V, (mi, ri)),
        f'{WR(mi,ri)} == "{winner}"',
        f"{lo} <= {V} && {V} < {hi}",
    ])


def build_C008(): return _per_match_longest(0, 4, 116222, "pinglamb", 116150, 116250)
def build_C009(): return _per_match_longest(1, 2, 179950, "yachi", 179950, 180050)
def build_C010(): return _per_match_longest(2, 2, 240131, "yachi", 240050, 240150)
def build_C011(): return _per_match_longest(3, 4, 83945, "pinglamb", 83850, 83950)
def build_C012(): return _per_match_longest(4, 0, 140000, "yachi", 139950, 140050)
def build_C013(): return _per_match_longest(5, 4, 95111, "pinglamb", 95050, 95150)
def build_C014(): return _per_match_longest(6, 2, 101797, "pinglamb", 101750, 101850)


def build_C015(): return build_C007()
def build_C016(): return build_C006()


def build_C017():
    V = 17
    ce, cv = count_expr([(f"{S(mi,ri,pl,'maxspike')} == {V}", pobj(mi, ri, pl)["maxspike"] == V) for (mi, ri, pl) in ALLPP])
    le = bal("&&", [f"{S(mi,ri,pl,'maxspike')} <= {V}" for (mi, ri, pl) in ALLPP])
    return andjoin([
        f"({S(4,7,'pinglamb','maxspike')} == {V}) && ({le})",
        eq(ce, cv), f"{cv} == 1",
        f"{MI(4)} == 5",
    ])


def build_C018():
    diffs = bal("&&", [f"({wq(mi,ri)} - {lq(mi,ri)}) <= 20" for (mi, ri) in ROUNDS])
    return andjoin([
        f"{MI(6)} == 7",
        f'{WR(6,2)} == "pinglamb"',
        f"{geSum(6,2,'pinglamb')} == 67",
        f"{geSum(6,2,'yachi')} == 47",
        f"({wq(6,2)} - {lq(6,2)}) == 20",
        diffs,
    ])


def build_C019():
    return andjoin([f"{wval(mi,ri,'vs')} > {lval(mi,ri,'vs')}" for (mi, ri) in ROUNDS])


def build_C020():
    P, _ = sum_field("pinglamb", "pieces")
    M, _ = sum_field("pinglamb", "lifetime")
    Y, _ = sum_field("yachi", "pieces")
    N, _ = sum_field("yachi", "lifetime")
    return andjoin([
        f"{P} * {N} < {Y} * {M}",
        f"{agg_pps_2dp('pinglamb')} == 132",
        f"{agg_pps_2dp('yachi')} == 141",
    ])


BUILDERS = {f"C{n:03d}": globals()[f"build_C{n:03d}"] for n in range(1, 21)}


def slug(g):
    return re.sub(r"[^a-zA-Z0-9]+", "_", g).strip("_").lower()[:60]


def emit_claims():
    claims = json.load(open(os.path.join(HERE, "claims-24.json")))
    lines = ["// Claims24.dfy — GENERATED by codegen_dafny.py. DO NOT EDIT.",
             'include "Facts24.dfy"', ""]
    mapping = []
    for c in claims:
        cid = c["id"]
        ens = BUILDERS[cid]()
        name = f"{cid}_{slug(c['english_gloss'])}"
        lines += [f"// {cid}: {c['english_gloss']}",
                  f"// python_check: {c['python_check']}",
                  f"lemma {name}()", f"  ensures {ens}", "{", "}", ""]
        mapping.append({"id": cid, "lemma": name, "file": "dafny/Claims24.dfy"})
    return "\n".join(lines), mapping


def lemma_index():
    _, m = emit_claims()
    return m



CONST_LINE = re.compile(r"^const (\w+)\s*:")


def keep_referenced(facts_src, claims_srcs):
    """Drop consts no lemma reads.

    A const nothing reads is data the proofs do not depend on, so a mutation of it
    can never be killed — it makes the anti-vacuity gate report survivors that mean
    nothing. pipeline/codegen.py filters the generated ledger the same way.
    """
    body = " ".join(claims_srcs)
    out = []
    for line in facts_src.split("\n"):
        m = CONST_LINE.match(line)
        if m and not re.search(rf"\b{m.group(1)}\b", body):
            continue
        out.append(line)
    return "\n".join(out)


def main():
    os.makedirs(OUT, exist_ok=True)
    src, _ = emit_claims()
    # Facts24.dfy is written last, carrying only the consts the lemmas actually read.
    with open(os.path.join(OUT, "Facts24.dfy"), "w") as f:
        f.write(keep_referenced(emit_facts(), [src]))
    with open(os.path.join(OUT, "Claims24.dfy"), "w") as f:
        f.write(src)
    print("generated 20 lemmas -> dafny/Facts24.dfy, dafny/Claims24.dfy "
          "(proof map written separately by build_proof_map.py from real verifier results)")


if __name__ == "__main__":
    main()
